
-- RESTAURATION DE LA BDD HARMONIE DU 23/01/2025 à 12h00 sur PP_HARMONIE
-- Requêtes de mise à jour de la configuration (Opus Activité de PP_HARMONIE déployé sur isival)

-- Update PROGRAM_PROPERTY
update SIH2_ADAGIO_DBA.PROGRAM_PROPERTY set NAME = 'https://opus-activite.isival.ifremer.fr/assets/img/logo/logo-sih-black.png' where LABEL = 'sumaris.activityCalendar.report.form.header.left.logo.url' and PROGRAM_FK = 'SIH-ACTIFLOT';
update SIH2_ADAGIO_DBA.PROGRAM_PROPERTY set NAME = 'https://opus-activite.isival.ifremer.fr/assets/img/logo/logo-sih-actiflot.png' where LABEL = 'sumaris.activityCalendar.report.form.header.right.logo.url' and PROGRAM_FK = 'SIH-ACTIFLOT';

-- Update SOFTWARE_PROPERTY
update SIH2_ADAGIO_DBA.SOFTWARE_PROPERTY set NAME = 'https://opus-activite.isival.ifremer.fr/' where LABEL = 'server.app.url' where SOFTWARE_FK = 61;
update SIH2_ADAGIO_DBA.SOFTWARE_PROPERTY set NAME = 'https://opus-activite.isival.ifremer.fr/assets/img/logo/logo-sih.png' where LABEL = 'sumaris.logo' where SOFTWARE_FK = 61;
update SIH2_ADAGIO_DBA.SOFTWARE_PROPERTY set NAME = 'https://opus-activite.isival.ifremer.fr/assets/doc/terms_of_use_fr.md' where LABEL = 'sumaris.termsOfUse.url' where SOFTWARE_FK = 61;
update SIH2_ADAGIO_DBA.SOFTWARE_PROPERTY set NAME = 'https://opus-activite.isival.ifremer.fr/assets/doc/privacy_policy_fr.md' where LABEL = 'sumaris.policy.url' where SOFTWARE_FK = 61;


commit;


-- Requêtes de récupération des données sur PP_HARMONIE (calendrier 3458660 validation : https://opus-activite.isival.ifremer.fr/activity-calendar/3458660)

-- Requêtes d'insert sur le calendrier 3458660 HARMONIE

-- ACTIVITY_CALENDAR
SELECT * FROM ACTIVITY_CALENDAR WHERE ID IN (
    SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3458660
);


-- Inutile


-- ACTIVITY_CALENDAR2PERSON
SELECT * FROM ACTIVITY_CALENDAR2PERSON WHERE ACTIVITY_CALENDAR_FK IN (
    SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3458660
);

-- Inutile
-- Déja renseigné (requête SQL de remplissage de ACTIVITY_CALENDAR2PERSON exécutée après l'import)

-- SURVEY_MEASUREMENT
SELECT * FROM SURVEY_MEASUREMENT WHERE ACTIVITY_CALENDAR_FK IN (
    SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3458592
);

-- Inutile

-- GEAR_PHYSICAL_FEATURES
SELECT * FROM GEAR_PHYSICAL_FEATURES WHERE ACTIVITY_CALENDAR_FK IN (
        SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3458660
    );

INSERT INTO SIH2_ADAGIO_DBA.GEAR_PHYSICAL_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, VESSEL_FK, QUALITY_FLAG_FK, PROGRAM_FK, PHYSICAL_GEAR_SURVEY_FK, FISHING_TRIP_FK, GEAR_FK, RANK_ORDER, OTHER_GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, HASH)
VALUES(16906721, TIMESTAMP '2024-01-01 00:00:00.000000', TIMESTAMP '2024-12-31 00:00:00.000000', TIMESTAMP '2025-01-16 00:00:00.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:32.571607', '899783', '1', 'SIH-ACTIFLOT', NULL, NULL, 51, 1, NULL, 3458660, 372, NULL);

-- GEAR_PHYSICAL_MEASUREMENT
SELECT * FROM GEAR_PHYSICAL_MEASUREMENT WHERE GEAR_PHYSICAL_FEATURES_FK IN (
    SELECT ID FROM GEAR_PHYSICAL_FEATURES WHERE ACTIVITY_CALENDAR_FK IN (
        SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3458660
        )
);

INSERT INTO SIH2_ADAGIO_DBA.GEAR_PHYSICAL_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, GEAR_PHYSICAL_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(29728476, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, 2568, NULL, NULL, 16906721, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_PHYSICAL_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, GEAR_PHYSICAL_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(29728477, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, 2567, NULL, NULL, 16906721, NULL);

-- GEAR_USE_FEATURES
SELECT * FROM GEAR_USE_FEATURES WHERE ACTIVITY_CALENDAR_FK IN (
    SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3458660
);

INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377432, TIMESTAMP '2024-06-01 00:00:00.000000', TIMESTAMP '2024-06-30 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:28.475415', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377433, TIMESTAMP '2024-01-01 00:00:00.000000', TIMESTAMP '2024-12-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:28.744784', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 49, 3458660, 539, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377434, TIMESTAMP '2024-01-01 00:00:00.000000', TIMESTAMP '2024-12-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:29.007917', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377435, TIMESTAMP '2024-11-01 00:00:00.000000', TIMESTAMP '2024-11-30 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:29.279708', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377436, TIMESTAMP '2024-10-01 00:00:00.000000', TIMESTAMP '2024-10-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:29.539738', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377437, TIMESTAMP '2024-04-01 00:00:00.000000', TIMESTAMP '2024-04-30 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:29.791760', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377438, TIMESTAMP '2024-01-01 00:00:00.000000', TIMESTAMP '2024-01-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:30.054424', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 49, 3458660, 539, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377439, TIMESTAMP '2024-01-01 00:00:00.000000', TIMESTAMP '2024-01-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:30.393868', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377440, TIMESTAMP '2024-09-01 00:00:00.000000', TIMESTAMP '2024-09-30 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:30.672902', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377441, TIMESTAMP '2024-05-01 00:00:00.000000', TIMESTAMP '2024-05-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:30.982630', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377442, TIMESTAMP '2024-02-01 00:00:00.000000', TIMESTAMP '2024-02-29 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:31.279884', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377443, TIMESTAMP '2024-08-01 00:00:00.000000', TIMESTAMP '2024-08-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:31.555561', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377444, TIMESTAMP '2024-07-01 00:00:00.000000', TIMESTAMP '2024-07-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:31.822646', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377445, TIMESTAMP '2024-12-01 00:00:00.000000', TIMESTAMP '2024-12-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:32.082203', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, FISHING_EFFORT_CALENDAR_FK, OPERATION_FK, GEAR_FK, ACTIVITY_CALENDAR_FK, METIER_FK, DAILY_ACTIVITY_CALENDAR_FK, ECONOMICAL_SURVEY_FK, OTHER_GEAR_FK, RANK_ORDER, HASH)
VALUES(61377446, TIMESTAMP '2024-03-01 00:00:00.000000', TIMESTAMP '2024-03-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:28:09.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:32.325317', '0', '899783', 'SIH-ACTIFLOT', NULL, NULL, 51, 3458660, 372, NULL, NULL, NULL, 1, NULL);

-- GEAR_USE_MEASUREMENT
SELECT * FROM GEAR_USE_MEASUREMENT WHERE GEAR_USE_FEATURES_FK IN (
    SELECT ID FROM GEAR_USE_FEATURES WHERE ACTIVITY_CALENDAR_FK IN (
            SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3464836
        )
);

INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, GEAR_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(32058739, 18, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, 177, NULL, NULL, 61377433, NULL);
INSERT INTO SIH2_ADAGIO_DBA.GEAR_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, GEAR_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(32058740, 1000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '1', NULL, NULL, 177, NULL, NULL, 61377434, NULL);

-- FISHING_AREA
SELECT * FROM FISHING_AREA WHERE GEAR_USE_FEATURES_FK IN (
    SELECT ID FROM GEAR_USE_FEATURES WHERE ACTIVITY_CALENDAR_FK IN (
            SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3458660
        )
);

INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742801, NULL, NULL, 15, 2055, 61377432, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742800, NULL, NULL, 15, 2090, 61377432, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742803, NULL, NULL, 15, 2090, 61377435, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742802, NULL, NULL, 15, 2124, 61377435, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742805, NULL, NULL, 15, 2090, 61377436, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742804, NULL, NULL, 15, 2124, 61377436, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742806, NULL, NULL, 15, 2055, 61377437, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742807, NULL, NULL, 15, 2091, 61377437, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742808, NULL, NULL, 11, 2054, 61377438, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742809, NULL, NULL, 15, 2091, 61377438, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742811, NULL, NULL, 15, 2090, 61377439, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742810, NULL, NULL, 15, 2091, 61377439, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742812, NULL, NULL, 15, 2091, 61377440, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742813, NULL, NULL, 15, 2124, 61377440, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742814, NULL, NULL, 15, 2090, 61377441, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742815, NULL, NULL, 15, 2091, 61377441, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742817, NULL, NULL, 15, 2090, 61377442, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742816, NULL, NULL, 15, 2124, 61377442, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742819, NULL, NULL, 15, 2124, 61377443, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742818, NULL, NULL, 15, 2161, 61377443, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742820, NULL, NULL, 15, 2124, 61377444, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742821, NULL, NULL, 15, 3429, 61377444, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742823, NULL, NULL, 15, 2091, 61377445, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742822, NULL, NULL, 15, 2124, 61377445, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742825, NULL, NULL, 15, 2090, 61377446, NULL, NULL, NULL, NULL, '0', NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.FISHING_AREA
(ID, NEARBY_SPECIFIC_AREA_FK, DEPTH_GRADIENT_FK, DISTANCE_TO_COAST_GRADIENT_FK, LOCATION_FK, GEAR_USE_FEATURES_FK, VESSEL_USE_FEATURES_FK, PRODUCE_FK, SAMPLE_FK, SALE_FK, QUALITY_FLAG_FK, QUALIFICATION_COMMENTS, QUALIFICATION_DATE)
VALUES(402742824, NULL, NULL, 15, 2092, 61377446, NULL, NULL, NULL, NULL, '0', NULL, NULL);

-- VESSEL_USE_FEATURES
SELECT * FROM VESSEL_USE_FEATURES WHERE ACTIVITY_CALENDAR_FK IN (
    SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3458660
);

INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910316, TIMESTAMP '2024-01-01 00:00:00.000000', TIMESTAMP '2024-01-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:25.131251', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910317, TIMESTAMP '2024-04-01 00:00:00.000000', TIMESTAMP '2024-04-30 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:25.403116', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910318, TIMESTAMP '2024-05-01 00:00:00.000000', TIMESTAMP '2024-05-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:25.668150', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910319, TIMESTAMP '2024-07-01 00:00:00.000000', TIMESTAMP '2024-07-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:25.945712', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910320, TIMESTAMP '2024-08-01 00:00:00.000000', TIMESTAMP '2024-08-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:26.200851', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910321, TIMESTAMP '2024-11-01 00:00:00.000000', TIMESTAMP '2024-11-30 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:26.452980', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910322, TIMESTAMP '2024-12-01 00:00:00.000000', TIMESTAMP '2024-12-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:26.723372', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910323, TIMESTAMP '2024-09-01 00:00:00.000000', TIMESTAMP '2024-09-30 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:27.055755', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910324, TIMESTAMP '2024-02-01 00:00:00.000000', TIMESTAMP '2024-02-29 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:27.317640', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910325, TIMESTAMP '2024-03-01 00:00:00.000000', TIMESTAMP '2024-03-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:27.653864', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910326, TIMESTAMP '2024-06-01 00:00:00.000000', TIMESTAMP '2024-06-30 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:27.929275', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_FEATURES
(ID, START_DATE, END_DATE, CREATION_DATE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, UPDATE_DATE, QUALITY_FLAG_FK, VESSEL_FK, PROGRAM_FK, IS_ACTIVE, FISHING_EFFORT_CALENDAR_FK, ACTIVITY_CALENDAR_FK, FISHING_TRIP_FK, OPERATION_FK, BASE_PORT_LOCATION_FK, ECONOMICAL_SURVEY_FK, DAILY_ACTIVITY_CALENDAR_FK, HASH)
VALUES(258910327, TIMESTAMP '2024-10-01 00:00:00.000000', TIMESTAMP '2024-10-31 00:00:00.000000', TIMESTAMP '2025-01-16 12:12:27.000000', NULL, NULL, NULL, NULL, TIMESTAMP '2025-01-16 12:31:28.215432', '0', '899783', 'SIH-ACTIFLOT', 1, NULL, 3458660, NULL, NULL, 563, NULL, NULL, NULL);

-- VESSEL_USE_MEASUREMENT
SELECT * FROM VESSEL_USE_MEASUREMENT WHERE VESSEL_USE_FEATURES_FK IN (
    SELECT ID FROM VESSEL_USE_FEATURES WHERE ACTIVITY_CALENDAR_FK IN (
            SELECT ID FROM ACTIVITY_CALENDAR ac WHERE PROGRAM_FK = 'SIH-ACTIFLOT' AND YEAR=2024 AND ID = 3458660
        )
);

INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179053, 12, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910316, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179054, 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910316, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179055, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910316, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179056, 15, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910317, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179057, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910317, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179058, 10, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910317, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179059, 9, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910318, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179060, 9, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910318, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179061, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910318, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179062, 17, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910319, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179063, 19, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910319, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179064, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910319, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179065, 12, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910320, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179066, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910320, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179067, 10, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910320, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179068, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910321, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179069, 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910321, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179070, 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910321, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179071, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910322, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179072, 13, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910322, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179073, 12, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910322, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179074, 13, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910323, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179075, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910323, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179076, 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910323, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179077, 12, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910324, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179078, 12, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910324, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179079, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910324, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179080, 13, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910325, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179081, 14, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910325, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179082, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910325, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179083, 11, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910326, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179084, 12, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910326, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179085, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910326, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179086, 15, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 242, NULL, NULL, 258910327, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179087, 3, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 109, NULL, NULL, 258910327, NULL);
INSERT INTO SIH2_ADAGIO_DBA.VESSEL_USE_MEASUREMENT
(ID, NUMERICAL_VALUE, DIGIT_COUNT, PRECISION_VALUE, CONTROL_DATE, VALIDATION_DATE, QUALIFICATION_DATE, QUALIFICATION_COMMENTS, DEPARTMENT_FK, PRECISION_TYPE_FK, QUALITY_FLAG_FK, ANALYSIS_INSTRUMENT_FK, NUMERICAL_PRECISION_FK, PMFM_FK, QUALITATIVE_VALUE_FK, AGGREGATION_LEVEL_FK, VESSEL_USE_FEATURES_FK, ALPHANUMERICAL_VALUE)
VALUES(802179088, 15, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '0', NULL, NULL, 241, NULL, NULL, 258910327, NULL);

