@startsalt

{
    {
                         | [Rechercher...]
    }
    ..

    {
        {/ <b> Détails | Sous-engins }
    }

    {
      Engin : | { ^ OTT - Chaluts jumeaux à panneaux ^ }
      Libellé : | { "                       " }
    }

    {
        <b>Commentaire :

        { "                                                                    "}
    }

  --

  {
    [Annuler] | [Valider]
  }
}
@endsalt
