@startsalt
 {+
  {  [ <&arrow-left> ] | <b>Partie retenue - Lot MNZ - Baudroie - Mesures individuelles | [<&check>] }

  --

  {
	{#
      # | <b>Espèce commerciale        |  <b>Longueur totale (cm)
      <color:blue>7 | <color:blue> MNZ- Baudroie             | <color:blue>46
      6 | MNZ- Baudroie             | 41
      5 | MNZ- Baudroie             | 20
      4 | MNZ- Baudroie             | 20
      3 | MNZ- Baudroie             | 15
      2 | MNZ- Baudroie             | 11
      1 | MNZ- Baudroie             | 10
    } | {
        {
          Longueur totale (cm) | "                         "
        }
        --
        { [<color:blue>Ajouter] }

        { [<color:blue>Terminer et nouveau] | [<color:blue>Terminer] }
      }
    }
  }
@endsalt
