@startuml
hide empty members


class SamplingScheme <<Entity>> {
  +id: Integer
  +label: String
  +name: String
  +description: String [0..1]
  +comments: String [0..1]
  +creationDate: Date
  +updateDate: Date
}

SamplingScheme "*" -up-> "1" Program

class SamplingStrata <<Entity>>{
  +id: Integer
  +label: String
  +name: String [0..1]
  +startDate: Date [0..1]
  +endDate: Date [0..1]
  +description: String [0..1]
  +comments: String [0..1]
  +creationDate: Date
  +updateDate: Date
}

class SamplingStrataMeasurement <<Measurement>>{

}


class AppliedSamplingStrata <<Entity>> #yellow{
  +id: integer
  +location: Location;
  +expectedEffort: integer[0..1]
}

class SamplingStrataAppliedPeriod <<Entity>>#yellow{
  +startDate: Date
  +endDate: [0..1]
}
class TaxonGroupSamplingStrata <<Entity>>#yellow{
  +priorityLevel : Integer[0..1]
}

SamplingScheme "1" *-down- "*" SamplingStrata
SamplingStrata "*" -up-> "1" Status
SamplingStrata "*" -left-> "0..1" Department
SamplingStrata "*" -left-> "0..1" Person

SamplingStrata "1" *--> "*" SamplingStrataMeasurement

SamplingStrata "*" -down-> "*" Grouping
SamplingStrata "*" -down-> "*" Fishery
SamplingStrata "*" -down-> "*" Vessel


SamplingStrata "*" *-right- "*" AppliedSamplingStrata
AppliedSamplingStrata "1" *-up- "1..*" SamplingStrataAppliedPeriod
SamplingStrata "1" *-- "*" TaxonGroupSamplingStrata
AppliedSamplingStrata "0..1" <-- "*" TaxonGroupSamplingStrata
TaxonGroupSamplingStrata "*" --> "1" TaxonGroup

legend right
  <back:yellow>Entité en jaune</back> : Nouvelle entité à créer,
  pour stocker les lignes de plans ObsVentes

end legend


@enduml
