@startsalt
 {+
  { Lot MNZ - Baudroie - <b>Mesures individuelles }
  ..
  .
  {
     . | . |   {+
        { | . | ()  <b>Mensurations | (X)  <b>Dénombrement | . | . | . | . | . }
        --
        { | . | Nombre d'individus *  | . | . | . | . | . | . }
        { | . | "   4  "  }
        .
        } . | . |
    }
    .
    {| . | . | . | . | . | . | . | . | [Annuler] | [Appliquer]}
  }
@endsalt
