@startsalt
{
    {+
        <color:ffffff>++ | <color:ffffff>++++ | <color:ffffff>++++++++ | <color:ffffff>+++++++++ | <color:ffffff>++ | . | <color:ffffff>++ | <color:ffffff>+++++++++ | <color:ffffff>++++++++ | <color:ffffff>++++ | <color:ffffff>++
        . | . | . | <size:16><b>Bienvenue sur le site web SUMARiS ! | * | * | * | * | . | . | .
        . | Base de données partagée pour des programmes de collecte de données halieutiques. | * | * | * | * | * | * | * | * | .
        . | . | . | . | . | . | . | . | . | . | .
        . | . | Vous n'avez actuellement aucun droit d'accès à un programme de collecte. | * | * | * | * | * | * | . | .
        . | . | . | . | . | . | . | . | . | . | .
        . | [<b><size:14><&account-login></size> DEMANDER L'ACCÈS À UN PROGRAMME DE COLLECTE           ] | * | * | * | * | * | * | * | * | .
        . | [<b><size:14><&person></size> MON COMPTE                                            ] | * | * | * | * | * | * | * | * | .
        . | . | . | . | Vous n'êtes pas <b>John DOE</b> ? | * | * | . | . | . | .
        . | . | . | . | . | <u>Déconnecter ce compte | . | . | . | . | .
        . | . | . | . | . | . | . | . | . | . | .
    }
}
@endsalt