@startsalt
 {+
  { Lot MNZ - Baudroie - <b>Mesures individuelles }
  ..
  <&trash>
  .

  {
	{#
      [].| .# | <b>Espèce scientifique | <b>Sexe | <b>Longueur totale (cm) | <b>Poids calculé RTP (kg)
      [].| 7 | ANK - Lophius budegassa   | Male | 46 | <color:blue>1.0173
      [].| 6 | ANK - Lophius budegassa   | Male | 41 | <color:blue>0.965
      [].| 5 | MON - Lophius piscatorius | Male | 20 | <color:blue>0.5874
      [].| 4 | ANK - Lophius budegassa   | Femelle | 20 | <color:blue>0.55
      [].| 3 | MON - Lophius piscatorius | Indetermine | 15 | <color:blue>0.4789
      [].| 2 | MON - Lophius piscatorius | Indetermine | 11 | <color:blue>0.3578
      [].| 1 | ANK - Lophius budegassa   | Indetermine | 10 | <color:blue>0.254
    } |

    {
      {+
        { | . |  <b>Ajouter une mesure :  | . }
        --
        { | . | Espèce scientifique *  | . }
        { | . | ^Lophius piscatorius^   | .  | [ ] Figer }
        .
        { | . | Sexe  | . }
        { | . | ^Femelle^  }
        .
        { | . | Longueur totale (cm) * | .  }
        { | . | "   12  "  }
        .
        { | . | <i>Poids calculé RTP (kg)  | . }
        { | . | "<color:blue>0.01335 " | .  }
        .
        { [                     Ajouter] }
        }
     }
    }
    {[Annuler] | [Appliquer]}
  }
@endsalt
