@startsalt
 {+
  { Lot MNZ - Baudroie - <b>Mesures individuelles (7) | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |<b> ...}
  ..
  <&trash> <color:grey><&spreadsheet></color> <&browser>

  {
	{#
      [].| .# | <b>Espèce scientifique | <b>Sexe | <b>Longueur totale (cm) | <b>Nombre d'individu | <b>Poids calculé RTP (kg)
      [].| 7 | ANK - Lophius budegassa   | Male | 46 | 1 | <color:blue>1.0173
      [].| 6 | ANK - Lophius budegassa   | Male | 41 | 2 |<color:blue>0.965
      [X].| 5 | MON - Lophius piscatorius | Male | 20 | 1 | <color:blue>0.5874
      [].| 4 | ANK - Lophius budegassa   | Femelle | 20 | 1 | <color:blue>0.55
      [].| 3 | MON - Lophius piscatorius | Indetermine | 15 | 1 | <color:blue>0.4789
      [].| 2 | MON - Lophius piscatorius | Indetermine | 11 | 1 | <color:blue>0.3578
      [].| 1 | ANK - Lophius budegassa   | Indetermine | 10 | 3 | <color:blue>0.254
    } |

    {
      {+
        { | . |  <b>Mensurations  | . | . | . | . | . }
        --
        { | . | Espèce scientifique *  | . }
        { | . | ^Lophius piscatorius^   | .  | [ ] Figer }

        { | . | Sexe  | . }
        { | . | ^Femelle^  }

        { | . | Longueur totale (cm) * | .  }
        { | . | "   12  "  }

        { | . | Nombre d'individu * | .  }
        { | . | "   1  "  | .   }

        { | . | <i>Poids calculé RTP (kg)  | . }
        { | . | "<color:blue>0.01335 " | .  }
        .
        { [                     Ajouter] }
        }
     }
    }
    {[Annuler] | [Appliquer]}
  }
@endsalt
