@startsalt
{
    **MNZ - Baudroie**

  {+
    { | . |  <b>Sélection du critère de classement numérique :  | . | . | . | . | . | . | . | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. }
    --
{
      Espèce scientifique :    | { ^Lophius piscatorius^ }

      Critère de classement :    | { ^Longueur totale (LT)^^<b>Paramètre,   Support, Fraction,  Méthode^^Longueur totale (LT), individu, totale, Mesure au 1/2 cm par un observateur^ }

      Méthode :    | <back:lightgrey><font color=black size=12>Mesure au 1/2 cm par un observateur

      Unité :   |  { ^ cm ^ }

      Minimum :   |  "17"

      Maximum : | "21"

      Précision de la mesure :    |  <back:lightgrey><font color=black size=12>0.5

      Instrument d'analyse : { ^ ^ }

  }
      --
    { [Valider] | [Annuler] }
    }
 }
@endsalt