@startsalt
{
    Lot MNZ - Baudroie - Cat.1 - Cat. UE0 - Etat : Frais - Prés. : Vivant - <b>Mensurations

  {+
    { | ()Mode rafale  | . | . |  (X)<b>Intervalle de taille | . | . | . | . | . | . | . | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. }
    --
{
      Espèce scientifique* :    | { ^Lophius piscatorius^ | <color:blue><b>Y}

      Critère de numérique* :    | { ^Longueur totale (LT)^^<b>Paramètre,   Support, Fraction,  Méthode^^Longueur totale (LT), individu, totale, Mesure au 1/2 cm par un observateur^ }

      Méthode de collecte:    | <back:lightgrey><font color=black size=12>Mesure au 1/2 cm par un observateur

      Minimum* <font size=10>(cm) :   |  "17"

      Maximum* <font size=10>(cm): | "21"

      Précision de la mesure <font size=10>(cm) :    |  <back:lightgrey><font color=black size=12>0.5

      Critère secondaire <font size=10>(qualitatif): { ^ Sexe ^ | [X]<font size=10>Tout sélectionner}

      { [   Appliquer] }

  }

    }
 }
@endsalt