@startsalt
 {+
  { Lot MNZ - Baudroie - <b>Dénombrement | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |<b> ...}
  ..
  <color:grey><&trash> <color:grey><&plus>

  {
	{#
      [].| .# | <b>Espèce scientifique | <b>Sexe | <b>Longueur totale (cm) | <b>Nombre d'individu | <b>Poids calculé RTP (kg) | .
      [].| 7 | <color:grey>ANK - Lophius budegassa   | <color:grey>Male | <color:grey>46 | <color:grey>1 | <color:grey>1.0173 | <color:grey><&image>
      [].| 6 | <color:grey>ANK - Lophius budegassa   | <color:grey>Male | <color:grey>41 | <color:grey>2 |<color:grey>0.965 | .
      [].| 5 | <color:grey>MON - Lophius piscatorius | <color:grey>Male | <color:grey>20 | <color:grey>1 | <color:grey>0.5874 | <color:grey><&image>
      [].| 4 | <color:grey>ANK - Lophius budegassa   | <color:grey>Femelle | <color:grey>20 | <color:grey>1 | <color:grey>0.55 | <color:grey><&image>
      [].| 3 | <color:grey>MON - Lophius piscatorius | <color:grey>Indetermine | <color:grey>15 | <color:grey>1 | <color:grey>0.4789 | .
      [].| 2 | <color:grey>MON - Lophius piscatorius | <color:grey>Indetermine | <color:grey>11 | <color:grey>1 | <color:grey>0.3578 | .
      [].| 1 | <color:grey>ANK - Lophius budegassa   | <color:grey>Indetermine | <color:grey>10 | <color:grey>3 | <color:grey>0.254 | <color:grey><&image>
    } |

 {+
    { | ()Mensurations  | . | . |  (X)<b>Dénombrement | . | . | . | . | . | . | . | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. }
    --
{
      Espèce scientifique* :    | { ^Lophius piscatorius^ }

      Critère de classement* :    | { ^Longueur totale (LT)^ }

      Méthode :    | <back:lightgrey><font color=black size=12>Mesure au 1/2 cm par un observateur

      Minimum* <font size=10>(cm) :   |  "17"

      Maximum* <font size=10>(cm): | "21"

      Précision de la mesure <font size=10>(cm) :    |  <back:lightgrey><font color=black size=12>0.5

      Critère secondaire <font size=10>(qualitatif): { ^ Sexe ^ }

      { [   Appliquer] }

  }

    }
    }

  }
@endsalt