@startsalt
{
    {+
        {* <size:16><b>  Programme de collecte}
        .
        { | . | . | . | . | Sélectionner le programme de collecte pour lequel demander les droits d'accès : | . | . | . | . | }
        { | . | . | . | . | ^DolphinFREE                                        ^ | . | . | . | . | }
        .
        { | . | . | . | . | [<b>Suivant] | [Annuler] | }
        .
    }
}
@endsalt