@startsalt
{
    {+
        {* <color:dddddd> | <size:16><b>Mon compte} | * | * | * | * | * | * | *
        <color:ffffff>++ | {/ <size:16> </size><size:18><&person></size><size:14><b> Profil                              </b></size> | <size:16> </size><size:18><&cog></size><size:14> Préférences                    </size> } | * | * | * | * | * | <color:ffffff>++
        . | . | . | . | . | . | . | .
        . | <color:ffffff>++ | Voici les données enregistrées concernant votre compte : | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | E-mail | * | * | * | * | .
        . | . | {+ <color:#9a9a9a>john.doe@ifremer.fr                                                                                                                                                            </color>} | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | Nom * | * | * | * | * | .
        . | . | {+ <size:12>DOE                                                                                                                                                                                    </size> } | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | Prénom * | * | * | * | * | .
        . | . | {+ <size:12>John                                                                                                                                                                                    </size> } | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | Organisme * | * | * | * | * | .
        . | . | {+ <color:#9a9a9a>Ifremer - Ifremer                                                                                                                                                                  </color>} | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | Programmes de collecte | * | * | * | * | .
        . | . | {+
                    <color:ffffff>++ | DOLPHINFREE - Programme DOLPHINFREE | <color:ffffff>+++ | <color:#9a9a9a>Validateur</color> | <color:ffffff>+++ | <i><color:#9a9a9a>Actif</color> | <color:ffffff>++ | <size:13> </size><size:16><&trash> | <color:ffffff>++
                    . | PIFIL2 - Programme de test des Pingers au filage (2024) | . | <color:#9a9a9a>Observateur    </color> | . | <i><color:#9a9a9a>En cours de validation   </color> | . | <size:13> </size><size:16><&trash> | .
                    . | <color:0000ff><size:14><&plus></size> AJOUTER | * | * | * | * | * | * | *
                } | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | <size:16><b>Sécurité | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | Mot de passe | * | * | <color:ffffff>+++++++++++++++++++++++++++++++++ | <color:0000ff>Changer le mot de passe <size:14><&chevron-right></size> | .
        . | . | . | . | . | . | . | .
        . | . | <size:16><b>Informations techniques | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | Profil utilisateur * | * | * | * | * | .
        . | . | {+ <color:#9a9a9a>Observateur                                                                                                                                                                        </color>} | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | Clé publique pour la signature numérique * | * | * | * | * | .
        . | . | {+ <color:#9a9a9a>ysSR6meONLX6YMx2CPzI1s0FoHv9VJJuM34LhogcRhhx                                                                                              </color>} | * | * | * | * | .
        . | . | . | . | . | . | . | .
        . | . | [<b>Sauvegarder] | . | [<size:14><&reload></size> Réinitialiser] | . | .
        . | . | . | . | . | . | . | .
    }
}
@endsalt