@startsalt
{
    {+
        {* <color:dddddd> | <size:16><b>Nouveau message} | * | * | * | * | *
        . | . | . | . | . | .
        <color:ffffff>++ |  Type d'envoi * | * | * | * | <color:ffffff>++
        . | ^<color:#9a9a9a>E-mail                                              ^ | * | * | * | .
        . | Destinataire * | * | * | * | .
        . | {+ <color:#9a9a9a>Superviseurs DolphinFREE                                                                                     </color> } | * | * | * | .
        . | Objet * | * | * | * | .
        . | {+ <color:#9a9a9a>Demande de droit d'accès au programme de collecte DolphinFREE                     </color> } | * | * | * | .
        . | Message * | * | * | * | .
        . | {+
                <size:12>Votre message...                                                                                                     </size>
                .
                .
                .
                .
                .
                .
            } | * | * | * | .
        . | . | . | . | . | .
        . | [<b>Envoyer] | . | [Annuler] | . | .
        . | . | . | . | . | .
    }
}
@endsalt