@startsalt
{
    {+
        {* <color:dddddd> | <size:16><b>Programme de collecte} | * | * | * | * | * | * | * | *
        . | . | . | . | . | .
        <color:ffffff>++ | Sélectionner le programme de collecte pour lequel demander les droits d'accès : | * | * | * | <color:ffffff>++
        . | ^DolphinFREE                                        ^ | * | * | * | .
        . | . | . | . | . | .
        . | [<b>Suivant] | . | [Annuler] | . | .
        . | . | . | . | . | .
    }
}
@endsalt