@startsalt
{
  <b>Weekly report of activity 02/02/2019 00:00 - LS-AF - Anse Forban
  ..
  {/ Information générale | Situation des navires | <b>Activités des navires }
  .| .| <&calendar> | [Fermer]
  {<size:16><b>Navire :            | { ^<size:16>SZ190 - Ziblo         ^ }}
{+
      {
        .
        <b>Liste des métiers:
        {Metier*:        | { ^FIXABSX - Active trap for Vyey^ | [] Valeur par défaut }  | [<&x>]}
        {Metier*:        | { ^METIER2 - Metier 2            ^ | [] Valeur par défaut }  | [<&plus>]| [<&x>]}
          .
        {Metier*:        | { ^FIXABSX - Active trap for Vyey^ | [] Valeur par défaut }  | [<&plus>]| [<&x>]}
      } |
      {
        [Lundi 02- <i>NA ] | [Mardi 03        ] | [Mercredi 04- <i>LD] | [<b>Jeudi 05- <i>NA ] | [ Vendredi 06] | [Samedi 07 ]   | [Dimanche 08]
        {[X] | [<&eye>]}   | {[ ] | <&eye>}     | {[ ] | <&eye>}       | {[X] | <&eye>}        | {[ ] | <&eye>} | {[ ] | <&eye>} | {[ ] | <&eye>}
        {[ ] | <&eye>}     | {[ ] | [<&eye>]}   | {[X] | [<&eye>]}     | {[X] | [<&eye>]}      | {[ ] | <&eye>} | {[ ] | <&eye>} | {[ ] | <&eye>}
        [Lundi 02- <i>DP ] | [Mardi 03        ] | [Mercredi 04- <i>IN] | [<b>Jeudi 05- <i>IN ] | [ Vendredi 06] | [Samedi 07 ]   | [Dimanche 08]
        {[X] | <&eye>}     | {[X] | <&eye>}     | {[X] | [<&eye>]}     | {[X] | [<&eye>]}      | {[ ] | <&eye>} | {[ ] | <&eye>} | {[ ] | <&eye>}
      }
}
.
      {<size:16><b>Navire :            | { ^<size:16>Navire 2             ^ }}
{+
      {
        .
        <b>Liste des métiers:
        {Metier*:        | { ^METIER1 - Metier 1            ^             | [] Valeur par défaut }  | [<&plus>]| [<&x>]}
      } |
      {
        [Lundi 02- <i>NA ] | [Mardi 03        ] | [Mercredi 04- <i>LD] | [<b>Jeudi 05- <i>NA ] | [ Vendredi 06] | [Samedi 07 ]   | [Dimanche 08]
        {[ ] | [<&eye>]}   | {[ ] | <&eye>}     | {[X] | [<&eye>]}     | {[X] | <&eye>}        | {[ ] | <&eye>} | {[ ] | <&eye>} | {[ ] | <&eye>}
      }
}
      {. |  {[Ajouter un navire] | [Annuler le dernier]}}
..
  {[Sauvegarder]}
}
@endsalt
