@startsalt
{
  <b>Weekly report of activity 02/02/2019 00:00 - LS-AF - Anse Forban
  ..
  {/ Information générale | <b>Situation des navires | Activités des navires }
  .
  {SI .| .| [Fermer]
      {
      {+
          <b>Liste navires:
          .
          .
          {{ ^SZ190 - Ziblo         ^ | [<&x>]}}
          .
          .
          {{ ^Vessel 2              ^ | [<&x>]}}
          .
          {{ ^Vessel 3              ^ | [<&x>]}}
          .
          {{ ^Vessel 4              ^ | [<&plus>] | [<&x>]}}
          .
      }
      } |
      {
          {
            {[<b>Lundi       ]} | {[<b>Mardi       ]} | {[<b>Mercredi    ]} | {[<b>Jeudi       ]} | {[<b>Vendredi    ]} | {[Samedi      ]} | {[Dimanche    ]}
            .
            { ^NA-... ^ | {[<&plus>]}} | { ^<i>Situation^} | { ^LD-... ^| {[<&plus>]}} | { ^NA-... ^} | { ^<b>BR-... ^| {[<&plus>]}} | { ^<i>Situation^} | { ^<i>Situation^}
            .           | .            | .                 | { ^IN-... ^  | {[<&plus>] | [<&x>]}}     | .                            | .                 | .
            .
            { ^DL-... ^| {[<&plus>]}} | { ^<i>Situation^} | { ^NA-... ^| {[<&plus>]}} | { ^NA-... ^| {[<&plus>]}} | { ^<b>LD-... ^| {[<&plus>]}} | { ^<i>Situation^} |  { ^<i>Situation^}
            .
            { ^IN-... ^| {[<&plus>]}} | { ^<i>Situation^} | { ^NA-... ^| {[<&plus>]}} | { ^OUT-...^| {[<&plus>]}} | { ^<b>DL-... ^| {[<&plus>]}} | { ^<i>Situation^} |  { ^<i>Situation^}
            .
            { ^NA-... ^| {[<&plus>]}} | { ^<i>Situation^} | { ^OUT-...^| {[<&plus>]}} | { ^NA-... ^| {[<&plus>]}} | { ^<b>LD-... ^| {[<&plus>]}} | { ^<i>Situation^} |  { ^<i>Situation^}
            .
          }
      }
  }
  ..
  {{[Sauvegarder] | [Saisir une activité]}}
}
@endsalt
