@startsalt
{
  <b>Nouveau weekly report
  ..
  {/ <b>Information générale | Activités des navires }
  .
  Programme de collecte*:    | { ^SIH-OBSDEB^ }
  Navire*:                   | { ^SZ190 - Ziblo^ | [<&plus>] }
  Lieu de débarquement de la marée*:     | { ^LS-AF - Anse Forban^ }
  Date/Heure début de marée:  | { ^02/02/2019^ | ^00:00^ }
  Date/Heure fin de marée:  | { ^08/02/2019^ | ^23:59^ }
  Observateurs :            | { ^Observateur #1^ | [<&plus>] | [<&x>]}
  .
  Commentaires              | { "commentaires       "}

  -- | --

  .                          | {[Annuler] | [Sauvegarder]}
}
@endsalt
