@startsalt
{
  <b>Weekly report of activity 02/02/2019 00:00 - LS-AF - Anse Forban
  ..
  {/ Information générale | Situation des navires | <b>Activités des navires }
  .| <&calendar> | [Fermer]
  {{+
    { <size:16><b>Navire :            | { ^<size:16>SZ190 - Ziblo                      ^ }}
    {+<back:RoyalBlue>                                  <color:white><b>JEUDI</b>      - 2 février 2019 -    <b><i>NA- boat not active</b>                     .}
    {() Métiers pratiqués }
    {+<back:RoyalBlue>                                  <color:white><b>JEUDI</b>      - 2 février 2019 -    <b><i>IN- boat in at site</b>                          .}
    {
    {(X) Métiers pratiqués } .|Fishing Trip

        {Metier*:        | { ^FIXABSX - Active trap for Vyey^ } | [<&x>]} |.| [<&eye>]

        {Metier*:        | { ^METIER2 - Metier 2            ^ }  | [<&plus>]| [<&x>]} |.| <&eye>
    }
  } [<&x>]}
  .
  {{+

  { <size:16><b>Navire :            | { ^<size:16>Navire 2                           ^ }}
    {+<back:RoyalBlue>                                  <color:white><b>JEUDI</b>      - 2 février 2019 -    <b><i>DP- boat departing that day</b>      .}
  {
    {(X) Métiers pratiqués } .|Fishing Trip
        {Metier*:        | { ^FIXABSX - Active trap for Vyey^ } | [<&x>]} |.| <&eye>

        {Metier*:        | { ^METIER3 - Metier 3            ^ }  | [<&plus>]| [<&x>]} |.| <&eye>
  }
  } [<&plus>] | [<&x>]}
  .
  {[Sauvegarder]}
}
@endsalt
