@startsalt
{
  <b>Nouvelle sortie
  --
  {/  Détails | <b> Échantillonnages }
  ..
  <&plus>
  .
	{#

      # |<b>Priorité | <b>Espèce commerciale | <b>Espèce scientifique   | <b>Navire | <b>Type de vente | <b>Raison de non observation | <b>Commentaire
      [X] . | 1 | POL - Lieu jaune | POL - Pollachius pollachius | 851751- Navire 1 | { ^Enchères - HAM / Criées^} | . | .
      [X] . | 2 | MNZ - Baudroie | . | 851751 - Navire 1 | { ^Enchères - HAM / Criées^} |. | .
      [ ] . | 3 | PIL - Sardine commune | PIL - Sardina pilchardus | . -|{ ^Enchères - HAM / Criées^} | ^ Espèce absente       ^ | .
      [X] . | 4 | NEP - Langoustine | NEP - Nephrops norvegicus   | 741541 - Navire 2 | { ^Enchères - HAM / Criées^} | . | .
      [ ] . | 5 | ... | . | . | .

    }
    { 15 espèces minimales observées (justifiez si non observée) }

    { (max: 30 espèces) }

    { ATTENTION: une même espèce peut-être tiré plusieurs fois }
  --


  {
    [Fermer] | [Sauvegarder]
  }
}
@endsalt
