@startsalt
{
  <b>Douarnenez - 08/02/2022
  --
  {/  Détails | Échantillonnages | <b><Autres espèces> (PETS)}
  ..
  { <&plus> <&trash> }

	{#

      [].| <b>Espèce commerciale | <b>Espèce scientifique  | <b>Navire | <b>Zone de pêche| <b>Type de vente | .
      [X]. | ^GAG - Requin-hâ ^ | ^GAG - Galeorhinus galeus^ | ^851751 - Navire 1^ | ^008B00 - CIEM VIIIb (Sud Gascogne)   ^ | ^Enchères - HAM / Criées^ | .
      []. | ^BSH - Peau bleue^ | ^                        ^ | ^851751 - Navire 1^ | ^008B00 - CIEM VIIIb (Sud Gascogne)   ^ | ^Enchères - HAM / Criées^ | <&comment-square>
    }
    .
  --


  {
    [Fermer] | [Sauvegarder]
  }
}
@endsalt
