@startsalt
{
  <b>Douarnenez - 08/02/2022
  --
  {/  <&info>Détails | <b> Échantillonnages <font color=blue size=8><b>(5)}
  ..

  { <&plus> <b>((<&plus>) <&reload> <&trash> } | <b>Y
	{#
      <&arrow-thick-top> | <b>Etat | <b>Espèce commerciale   | <b>Navire | <b>Zone de pêche|  <b>  ... | *
      [X] 1 | <&pencil> |   BET - Thon obèse(=Patudo) |  123456 - Navire 1 | Zone 1 |  . | <&tag>
      [] 2 |<&pencil>  |  BFT - Thon rouge de l'Atlantique  | 123456 - Navire 1 | Zone 2 |  <&comment-square> | <&tag>
      [X] 3 |<&pencil>  |  BIL - Makaires,marlins,voiliers nca  | . | . |  . | <&tag>
      [X] 4 |<&pencil>  | BLF - Thon à nageoires noires  | 456789 - Navire 2 | Zone 1 |  <&comment-square> | <&tag>
      [] 5 |<&pencil>  |  BLT - Bonitou |  . | . | . | .
      [] 6 | <&pencil>  | ... |  . | . | . | .
    }
  --

  {
    [Fermer] | [Sauvegarder]
  }
}
@endsalt
