@startsalt
{
  <b>Nouvelle sortie
  --
  {/ <b>Détails | Echantillonnages}
  ..
  .
  {

      Programme de collecte* :    | { ^SIH-OBSVENTE                ^ } | * | {^"<color:grey>Stratégie"
                                                                                              ObsVentes démarrage au 01/01/2024 <&eye>
                                                                                              <color:grey>Saisisseur
                                                                                              Obs1}
      Plan d'échantillonnage* :    | { ^2021_V0010 - DPMA_20_23_Lot2^}
      .
      Origine* :    | { ^SIH-OBSVENTE                ^ }
      .
      Lieu * :     | { ^XDZ - Douarnenez            ^ }
      .
      Début/Fin* :     | { ^jj/mm/aaaa^  |  ^hh:mm^ } { ^jj/mm/aaaa^  |  ^hh:mm^ } <i><color:blue>durée de la sortie
      .
      Observateur(s)* :            | ^ Observateur #1             ^ | { [<&plus>] | [<&x>] }
      .


  }

  <b>Caractéristiques :

  {
      . | Disponibilité de la fiche de pré-vente :| ^Oui^
      . | PETS ?* : | ^Oui^
      . | .
  }


  {
     <b>Commentaires :

     {+ .
        "                                                                                          "
     }
  }

  { [Fermer] | [Sauvegarder] }
}
@endsalt
