@startsalt
{
  <b>Nouvelle sortie
  ..
  {/ <b>Détails | Ventes }
  .
  {

      Programme de collecte* :    | { ^SIH-OBSVENTE^ }
      Lieu / Date* :     | { ^XDZ - Douarnenez^ } | { ^ jj/mm/aaaa^  |  ^ hh:mm^ }
      Observateurs* :            | ^ Observateur #1 ^ | { [<&plus>] | [<&x>] }
      .
  }

  {
     <b>Commentaires :

     {+ .
        "                                                               "
     }
  }

  { [Fermer] | [Sauvegarder] }
}
@endsalt
