@startsalt
{

  {<b>Sorties                                                                                                                                                                      <&reload>}
   --

    {
        Programme de collecte : | . | ^ SIH-OBSVENTE    ^
        .
        Lieu : | . | ^ XDZ - Douarnenez^
        .
        Début de la période : | . | ^01/01/2023       ^ | . | . | Fin de la période : | . | ^31/12/2023     ^
        .
        Organisme saisisseur :   | . | ^ Ifremer         ^ |  . | . | Saisisseur :   | . | ^ Nicolas DUPOND^
        .
        Observateurs : | . | ^ Nicolas DUPOND  ^ |  . | . | Etat :   | . | ^En cours de saisie ^

    }

  --
  {2 résultats  {}[<&caret-bottom>] | [Fermer] | [Appliquer]}}
}
@endsalt
