@startsalt
{
  <b>Ventes                                                                                                                                                                                              <&plus>
  --
	{#

     [ ]. | <b>Etat | <b>Navire | <b>Lieu de la vente | <b>Date/heure | <b>Saisisseur | <b>Référence au plan | .
     [ ]. | <b>  <&pencil> | 110854 - TETHYS | ESB - Erquy | 02/08/2022 05:00 | saisisseur1 | 2021_V0010 - DPMA_20_23_Lot2
     [ ]. | <b>  <&pencil> | 123444 - LA BARAKA | ESB - Erquy | 02/08/2022 05:00 | saisisseur1 | 2021_V0010 - DPMA_20_23_Lot | <&comment-square>
    }

}
@endsalt