@startsalt
{
  { Douarnenez - 08/02/2022 - <b>MAC - Maquereau commun - 123456 Navire 1  | . |   {* ...
                                                                                   ... | <&check> Remplissage de l'heure | de la vente }
                                                                                                                                                                                                                          }
  --
  {/  <b>Détails | Lots }
  ..
  {

      Navire* :    | { ^123456 - Navire 1                  ^ }
      .
      Type de vente* :    | { ^Enchères - HAM / Criées            ^ }
      .
      Date de la vente :   |  { ^ jj/mm/aaaa^  |  ^ hh:mm^ }
      .
      Zone de pêche :            | ^ 008B00 - CIEM VIIIb (Sud Gascogne)^
      .
  }

  Commentaires
  {+ .
          "                                                                     "
  }

}
@endsalt