@startuml
hide empty members

interface IReferentialItem {
    +id: Int
    +label: String
    +name: String
    +description: String [0..1]
    +comments: String [0..1]
    +updateDate: Timestamp
}

interface IReferentialLevel {
}

class Status {
    +id: int
    +label: String
    +name: String
    ...
}

enum StatusEnum {
   +DISABLE: 0
   +ENABLE: 1
   +TEMPORARY: 2
   +DELETED: 3
}

IReferentialItem "0..*" --> "1" Status
IReferentialItem "0..*" -right-> "0..1" IReferentialLevel: "has level"

Status <.left. StatusEnum: "is an identifier of"


@enduml
