@startuml
hide empty members

class Location {
    +id: int
    +label
    +name
}

class LocationLevel
{
    +id: int
    +label
    +name
}

Location "0..*" -right-> "1" LocationLevel: "      "
Location "0..*" --> "1" Status

enum "LocationLevelIds  " {
    COUNTRY: 1
    HARBOUR: 6
    AUCTION: 7
}
@enduml
