@startuml
hide empty members

  class SpatialItemType {
    + id : integer
    + label : string
    + description : string [0..1]
    + updateDate : timestamp [1]
  }

  class SpatialItem {
    + id : integer [1]
    + objectid : integer [1]
    + updateDate : timestamp [1]
  }

  class SpatialItemPoint {
    + id : integer [1]
    + localizedName : string [0..1]
    + position : multipoint [0..1]
  }

  class SpatialItemLine {
    + id : integer [1]
    + localizedName : string [0..1]
    + position : multilinestring [0..1]
  }

  class SpatialItemArea {
    + id : integer [1]
    + localizedName : string [0..1]
    + position : multipolygon [0..1]
  }

  class SpatialItem2Location {
    + localizedName : string [0..1]
  }


    package "referential" #DDDDDD {

      class Status

      class ObjectType

      class Location
  }

  enum SpatialItemTypeEnum {
    DEPTH_GRADIENT = 1
    NEARBY_SPECIFIC_AREA = 2
    DISTANCE_TO_COAST_GRADIENT = 3
    GEAR = 5
    TAXON_GROUP = 4
    METIER = 8
  }

  SpatialItemTypeEnum .left.> SpatialItemType: "is an\n identifier of"

  SpatialItemType "1" <-- "*" SpatialItem : type
  SpatialItemType "1" --> "*" Status : status
  SpatialItemType "1" --> "*" ObjectType : objectType

  SpatialItem "0..*" *-- "0..*" SpatialItem2Location : locations
  SpatialItem "0..*" *-- "0..*" SpatialItemPoint : geometry
  SpatialItem "0..*" *-- "0..*" SpatialItemLine : geometry
  SpatialItem "0..*" *-- "0..*" SpatialItemArea : geometry
  SpatialItem2Location "0..*" -- "1" Location
}

@enduml
