@startgantt
hide footbox

<style>
ganttDiagram {
    unstartedTask {
        FontName Helvetica
        FontColor Green
        FontSize 12
        FontStyle bold
        BackGroundColor DeepSkyBlue
        LineColor DeepSkyBlue
    }
    task {
        FontName Helvetica
        FontColor Black
        FontSize 12
        FontStyle bold
        BackGroundColor DeepSkyBlue
        LineColor DeepSkyBlue
    }
    milestone {
        FontColor black
        FontSize 12
        FontStyle bold
        BackGroundColor yellow
        LineColor FireBrick
    }
    note {
        FontColor DarkGreen
        FontSize 10
        LineColor OrangeRed
    }
    arrow {
        FontName Helvetica
        FontColor red
        FontSize 18
        FontStyle bold
        BackGroundColor GreenYellow
        LineColor blue
        LineStyle 8.0;13.0
        LineThickness 3.0
    }
    closed {
        BackgroundColor pink
        FontColor red
    }
}
</style>

printscale weekly
projectscale weekly

title Opus - ObsVentes - Development


!procedure N(x,n)
[x<size:0>n</size>]
!endprocedure

N(1, 1) as [o1] happen the 2024/02/29
N(1, 1) is colored in orange

N(2, 2) as [o2] happen the 2024/03/12
N(2, 2) is colored in orange

N(3, 3) as [o3] happen the 2024/03/26
N(3, 3) is colored in orange

N(4, 4) as [o4] happen the 2024/05/21
N(4, 4) is colored in orange

N(5, 5) as [o5] happen the 2024/09/10
N(5, 5) is colored in orange

N(6, 6) as [o6] happen the 2024/08/13
N(6, 6) is colored in orange

N(7, 7) as [o7] happen the 2024/12/02
N(7, 7) is colored in orange

N(8, 8) as [o8] happen the 2024/12/06
N(8, 8) is colored in orange

[o1] displays on same row as [o2]
[o2] displays on same row as [o3]
[o3] displays on same row as [o4]
[o4] displays on same row as [o5]
[o5] displays on same row as [o6]
[o6] displays on same row as [o7]
[o7] displays on same row as [o8]

today is colored in forestGreen

Project starts the 2024/03/04
[Training] as [TRAIN1] requires 1 week
[TRAIN1] is colored in Grey

[r2.9.16] as [TASK1] requires 4 weeks
[TASK1] is colored in Grey
[TRAIN1]->[TASK1]


[r2.9.17] as [TASK2] requires 3 weeks
[TASK2] is colored in Grey
[TASK1]->[TASK2]
[Testing2] requires 1 week and starts the 6th of May 2024
[TASK2]->[Testing2]

[pre-prod] as [PREPROD] requires 3 week and starts the 29th of April 2024
[PREPROD] is colored in salmon

[r2.9.18] as [TASK3] requires 4 weeks
[TASK3] is colored in grey
[TASK2]->[TASK3]
[Testing3] requires 1 week
[TASK3]->[Testing3]
[Demo 1 MOA] happens 3 day after [Testing3]'s end

[r2.9.19.2] as [TASK4] requires 4 weeks and starts the 27th of May 2024
[TASK4] is colored in grey
[TASK3]->[TASK4]
[Testing4] requires 1 week and starts 1th of July 2024
[TASK4]->[Testing4]
[Demo 2 MOA] happens 9th of July 2024

[r2.9.20] as [TASK5] requires 4 weeks and starts the 24th of June 2024
[TASK5] is colored in grey
[TASK4]->[TASK5]
[Testing5] requires 1 week and starts the 1th of August 2024
[TASK5]->[Testing5]

[r2.9.21] as [TASK6] requires 4 weeks and starts the 15th of July 2024
[r2.9.21] is colored in grey
[TASK5]->[TASK6]
[Testing6] requires 1 week and starts the 2 of Septembre 2024
[TASK6]->[Testing6]

[Atelier/Demo 3 MOA] happens the 10th of September 2024

[r2.9.22] as [TASK7] requires 3 weeks and starts the 19th of August 2024
[TASK7] is colored in grey
[TASK6]->[TASK7]
[Testing7] requires 1 week
[TASK7]->[Testing7]




[            ActiFlot development] as [ActivityCalendarMEP] requires 12 week and starts 11th September 2024
[ActivityCalendarMEP] is colored in lime

[ActiFlot test] as [ActivityCalendarMCO] requires 3 week and starts 1th December 2024
[ActivityCalendarMCO] is colored in lime

[ActivityCalendarMEP] displays on same row as [ActivityCalendarMCO]

[SIH] as [Séminaire SIH] requires 8 days and starts the 9th December 2024
[SIH] is colored in pink

[r2.10 draft] as [TASK8] requires 3 weeks and starts the 19th of November 2024
[TASK8] is colored in green
[TASK7]->[TASK8]

[Demo proto MOA] happens 0 day after [TASK8]'s end


[r2.11] as [TASK9] requires 4 weeks and starts the 9th of December 2024
[TASK9] is colored in Lavender/LightBlue
[TASK8]->[TASK9]
[Testing9] requires 1 week
[TASK9]->[Testing9]
[Demo MOA 5] happens 3 day after [Testing9]'s end

[r2.12] as [TASK10] requires 4 weeks and starts the 8th of January 2025
[TASK10] is colored in Lavender/LightBlue
[TASK9]->[TASK10]
[Testing10] requires 1 week
[TASK10]->[Testing10]
[Demo MOA 6] happens 3 day after [Testing10]'s end

[r2.13] as [TASK11] requires 4 weeks and starts the 5th of Febrary 2025
[TASK11] is colored in Lavender/LightBlue
[TASK10]->[TASK11]
[Testing11] requires 1 week
[TASK11]->[Testing11]
[Demo MOA 7] happens 3 day after [Testing11]'s end

[r2.14] as [TASK12] requires 3 weeks and starts the 4th of March 2025
[TASK12] is colored in Lavender/LightBlue
[TASK11]->[TASK12]
[Testing12] requires 1 week
[TASK12]->[Testing12]
[Demo MOA 8] happens 3 day after [Testing12]'s end

[r2.15] as [TASK13] requires 3 weeks and starts the 1th of April 2025
[TASK13] is colored in Lavender/LightBlue
[TASK12]->[TASK13]


[validation / Tests MCO] as [VAL] requires 1 week and starts the 10th of April 2025
[VAL] is colored in orange
[TASK13]->[VAL]

[Production] as [PROD] requires 1 week and starts the 2th of December 2024
[PROD] is colored in green
[VAL]->[PROD]

[validation] as [VAL] requires 1 week and starts the 1th of April 2025
[VAL] is colored in red


[GPR] as [CONG_GPR] requires 4 week and starts the 19th of July 2024
[VFA] as [CONG_VFA] requires 3 week and starts the 15th of August 2024
[CDE] as [CONG_CDE] requires 11 days and starts the 5th of september 2024
[GPR] is colored in lightgrey
[VFA] is colored in lightgrey
[CDE] is colored in lightgrey

[MSC] as [CONG_MSC] requires 4 week and starts the 29 of July 2024
[MSC] is colored in lightsteelblue

[JLT] as [CONG_JLT] requires 2 week and starts the 12 of August 2024
[JLT] is colored in lightsteelblue

[EBU] as [CONG_EBU] requires 4 week and starts the 15 of August 2024
[EBU] is colored in lightsteelblue

[JVF] as [CONG_JVF] requires 2 week and starts the 29th of July 2024
[JVF] is colored in plum
2024-07-29 to 2024-08-11 is colored in grey
2024-09-11 to 2024-11-18 is colored in grey

[MFA] as [CONG_MFA] requires 2 week and starts the 09th of October 2024
[MFA] is colored in plum

[BLE] as [CONG_BLE] requires 3 week and starts the 5th of August 2024
[BLE] is colored in plum

[BLE Pat] as [PAT_BLE] requires 1 week and starts the 28th of October 2024
[BLE Pat] is colored in plum
[BLE Pat] displays on same row as [BLE]

[MDE] as [CONG_MDE] requires 3 week and starts the 8th of July 2024
[MDE] is colored in plum

[CGFS 2 VFA] as [EMB] requires 3 week and starts the 31th of September 2024
[EMB] is colored in lightgrey

skinparam legendBackgroundColor with

legend
  |<#lightgrey>  | Congés/Abs. MOE |
  |<#lightsteelblue>  | Congés MOA |
  |<#plum>   | Congés Dev |
end legend

@endgantt
