@startsalt
{
  {/ Détails | <b> Capture }
  {
  <b> v Capture | [+]
   \t\tPartie retenue | [2] | [..]
   \t\tPartie rejetée, Vrac | [0] | [..]
   }
  --
  {
    [Fermer] | [Sauvegarder]
  }
}
@endsalt

