@startsalt
{

  {  <b> Nouvel engin | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |[Rechercher] }
  ..

     {
         <back:red><font color=white><i>Informations de saisie
     }
    .
    {
       <b>Engin : | ^GNC - Filets maillants encerclants^
    }
  .
    <b>Caractéristiques :
    {
      . | Hauteur du filet : |  "        "  | (m)
      . | Longueur levée* : |  "        "  | (m)
      . | Plus petit maillage à la jauge* : |  "        "  | (mm)
      . | Plus grand maillage à la jauge (trémail)* : |  "        "  | (mm)
      . | Type de fil majoritaire : | ^mono^
      . | Dispositifs de répulsif* : | ^Pas d'info^
      . | <&plus> Autres caractéristiques (cf "Grille de saisie")
    }
  --
    <b><&plus> <&minus> Navire associé
    {
    . | Immatriculation : | "68564" | . | . | . | . | . | Nom : | "Vessel 3"
    . | Quartie d'immatriculation : | "SN - Saint Nazaire" | . | . | . | . | . | Longueur hors tout (m) : | "2280"
    . | Capteur remontée sur le navire de l'observateur : | ^Oui^ | . | . | . | . | . | Longueur hors tout (m) : | "2280"
    . | Commentaire :
    . |  { "                                  "}
    }
  --
    {
        <b>Commentaire :

        { "                                                                                  "}
    }

  --

  {
    [Annuler] | [Sauvegarder]
  }
}
@endsalt
