@startsalt
{

  {/  Détails | <b> Engins | Opérations  }


	{#
      [ <&plus> ] |  .              | .
      # | <b>Engin     | <b>Type d'engin
      1 | OTT- Chalut jumeaux                | Chalut standard
    }

  --

  {
    [Fermer] | [Sauvegarder]
  }
}
@endsalt
