@startsalt
{

  {/  Détails | <b> Engins | Opérations  }


	{#
      [ <&plus> ] |  .              | .
      # | <b>Engins     | <b>Type d'engin   | <b> PSFM 2
      1 | OTT- Chalut jumeaux                | Chalut standard | Caractéristique 2
    }

  --

  {
    [Fermer] | [Sauvegarder]
  }
}
@endsalt
