@startsalt
{
{+
    .
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  <back:red><font color=black><size:16><b>Authentification  | . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  Email*  }
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  "                    "  | . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  Mot de passe*  }
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  "                    "  | <b><&eye> | . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  Noeud | . | . | . | . | . | . | . | . | . | . | . |<u>OBSMER| . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |   [Annuler]  | .| [Se Connecter] | . | . | . | . | . | . | . | . |}
    .
 }
}
@endsalt

