@startsalt
{
  {+
   {
       <b><font color=grey size=20>ACCUEIL    | . | . | . | . | . | . | .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
       .
   }

   {
      <font color=grey size=10>V XXX - à propos
   }
  } | . | {+
    .
    .
    .
    .
    .
    .
    .
    { ---------------
        { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  <back:red><font color=black><size:16><b>Authentification  | . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  Email*  }
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  "                    "  | . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  Mot de passe*  }
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  "                    "  | <b>(o) | . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |  Choix du noeud | . | . | ^OBSMER^| . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |   [Annuler]  | .| [Se Connecter] | . | . | . | . | . | . | . | . |}
    ---------------
    }
    .
    .
    .
    .
    .
    .
    .
    .
    .
    }
 }
  -- | -- | --

}
@endsalt

