@startsalt
{
  {+
    .
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . |   <back:red><font color=black><size:16><b>Authentification  | . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . |   Identifiant*  }
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . |   "                    "  | . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . |   Mot de passe*  }
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . |   "                    "  | <b><&eye> | . | . | . | . | . | . | . | . |}
    { | . | . | . | . | . | . | . | . | . | . | . | . | . | . |    [Annuler]  | .| [Se Connecter] | . | . | . | . | . | . | . | . |}
    .
    }
 }
@endsalt

