@startsalt
{
{<b>ObsMer                                                                                                           <&plus> <&reload> Y {[2024 <&chevron-bottom>] {* ...
                                                                                                                                                                                      ... |  <&signal>Editer le rapport ... <&chevron-right> | - | <b>Types de rapport | - | <&chevron-right> Formulaire terrain | <&chevron-right> Formulaire validation | <&chevron-right> Restitution aux professionnels }} }
  --


}
@endsalt