@startsalt
{

  {/ <b> Détails | Capture }
  ..

    {
      { Engin / espèce ciblée : | ^ FPN - Filet ^ | ^ Espèce cible ^ }
       .
      {
        Début de l'opération (Filage) : | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        Fin de l'opération (Filage) :   | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        Début de l'opération (Virage) : | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        Fin de l'opération (Virage) :   | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
      }
    }
    .
    <b>Caractéristiques :

    {
      . | Mesures individuelles ? { (X) <b>Oui | () Non }
      . | Déroulement normal ? { (X) <b>Oui | () Non }
      . | . | + Autres caractéristiques (cf "Grille de saisie")
    }
    .
    {
        <b>Commentaire :

        { "                                                                    "}
    }

  --

  {
    [Annuler] | [Sauvegarder]
  }
}
@endsalt
