@startsalt
{

  {/ <b> Détails | Capture }
  .
    {
      { Engin / espèce ciblée : | ^ OTB - Chalut de fond à panneaux^ | ^ Espèce cible ^ }
        .
      {
        Début de filage : | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        Début de pêche (Fin Filage) :   | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        Fin de pêche (Début Virage) : | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        Fin de virage :   | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        . | <i><color:blue>durée de l'opération | . | <i><color:blue>distance parcourue
      }
    }
    .
    {
    <b>Zone de pêche: <i><color:blue>22E7
    }
    .

    <b>Caractéristiques :

    {
      . | Opération échantillonnée ? { (X) <b>Oui | () Non }
      . | Déroulement normal ? { (X) <b>Oui | () Non }
      . | . | + Autres caractéristiques (cf "Grille de saisie")
    }

    {
        <b>Commentaire :

        { "                                                                    "}
    }

  --

  {
    [Annuler] | [Sauvegarder]
  }
}
@endsalt
