@startsalt
{
 {

   { <b><&arrow-left> CN851741 - Marée 07/01/2023 - OP #2 du 07/11/2023   |  . | . | . | . | ^LOG^}
--
<back:green><b><font color=white>Dernières opérations | .
{ <&check> 1 - OTB - Chaluts de fond à panneaux | . | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. | . | 10/11/2023 }
{ <&check> 2 - OTB - Chaluts de fond à panneaux | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | 10/11/2023 }
{ . | . | . | . | . | . | . | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |[Ajouter]}
    }
}
@endsalt

