@startsalt
{

  {/ <b> Détails | Capture }
  ..

    {
      { Engin / espèce ciblée : | ^ OTT - Chalut jumeau à panneaux ^ | ^ Espèce cible ^ }

      {
        Fin filage : | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        Début virage :   | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        . | <i><color:blue>durée de l'opération | . | <i><color:blue>distance parcourue
      }
    }
    .
    {
    <b>Zone d'activité : <i><color:blue>22E7
    }
    .

    <b>Caractéristiques :

    {
      . | Opération échantillonnée ? { (X) <b>Oui | () Non }
      . | Déroulement normal ? { (X) <b>Oui | () Non }
      . | . | + Autres caractéristiques (cf "Grille de saisie")
    }

    {
        <b>Commentaire :

        { "                                                                    "}
    }

  --

  {
    [Annuler] | [Sauvegarder]
  }
}
@endsalt
