@startsalt
{
  {+
    { | . |  <b>Ajouter une mesure :  | . }
    --
    { | . | Espèce scientifique *  | . }
    { | . | ^Lophius piscatorius^   | .  | [ ] Figer }
    .
    { | . | Longueur totale (cm) * | .  }
    { | . | "   12  "  }
    .
    { | . | <i>Poids calculé RTP (kg)  | . }
    { | . | "   0.01335 " | .  }
    .
    { [AJouter] }
    }
 }
@endsalt

