@startsalt
{
  <b> Capture / Partie retenue
  {/  <b> Lots par espèce | Mesures individuelles }
  	[ <&plus> ]
	{#
      [ ]  | # | <b> Espèce commerciale (FAO) | <b> Espèce scientifique   | <b> Devenir de l'espèce | <b> Poids total | <b> Nb indiv. total | <b> Nb estimé | <b> Tx échant. | <b> Poids échant. | <b> Nb indiv. échant
      [ ] | 1 | ^ SCR Araignée européenne ^ | ^ Maja brachydactyla ^ | ^ conso humaine ^ |  1.543  |  2 | [x] |  100 | 1.543  | 1
      [ ] | 2 | ^ CRE Toureau             ^ | ^ Cancer pagurus     ^ | ^ conso humaine ^ |  1.105  |  1 | [x] | 100 | 0.743  | 1
    }

  --

  {
    [Fermer] | [Sauvegarder]
  }
}
@endsalt

