@startsalt
{
  {  <&arrow-thick-left> Lot MNZ - Baudroie - <b>Mesures individuelles | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. | <&check>}
  	--
	{#
      [ ]  | # | <b> Espèce scientifique   | <b> Longueur totale (cm) | <b> Poids calculé RTP (kg) | <&menu>
      [ ] | 1 | ANK - Lophius budegassa | 22 | 0.1328 | .
      [ ] | 2 | ANK - Lophius budegassa | 12 | 0.0223 | .
    }

  --

  {
    [Appliquer]
  }
}
@endsalt

