@startsalt
{
  <b>Nouvelle marée
  ..
  {/ <b>Détails | Engins | Opérations }
  .
  {

      Programme de collecte*:    | { ^SIH-OBSMER                            ^ } | * {^"Stratégie"
Démarrage au 01/01/2023 }

      Référence*:  | { ^2021_M020 - DPMA_23_Lot4^ }  | * | {^"Saisisseur"
                                                                                                                   Nicolas DUPOND - Ifremer  } |.

      Programme de rattachement*: | { ^ DPMA_23_Lot4 ^ } |  . | <&calendar> Créé le 10/11/2023
      .
      Observateurs*:            | ^ Observateur #1    ^ | { [<&plus>] | [<&x>] } | <&calendar> Mis à jour le 10/11/2023

      Navire*:                   | { ^851751 - PETIT BAT ^ } | * | [Terminer la saisie]

      Départ*:     | { ^Port               ^ } | { ^ jj/mm/aaaa^ } | .
      . | { ^DRZ - Douarnenez   ^ } | { ^ hh:mm     ^ } | .

      Retour*:     | { ^Port               ^ } | { ^ jj/mm/aaaa^ } | .
      . | { ^DRZ - Douarnenez   ^ } | { ^ hh:mm     ^ } | .
      . | . | <i><color:blue>durée de la marée |
      .
      .
      Vente*:     | { ^Type de vente         ^ } | { ^ jj/mm/aaaa^ } | .
      .           | { ^Lieu de vente         ^ } |  { ^ hh:mm^ } |

  }

  <b>Caractéristiques :

  {
      . |Nombre d'hommes à bord : | " 4   "
      . |Caractéristique #2 : | ^Valeur qualitative^
      . |. | + autres caractéristiques (cf "Grille de saisie")
      . |.
  }

  {
     <b>Commentaire :

     {+ .
        "                                                               "
     }
  }

  { [Fermer] | [Sauvegarder] }
}
@endsalt
