@startsalt
{
  <b> Immat Navire - Lieu - Date fin marée - Métier
  ..
  {/ General trip | Effort | Capture débarquée | Vente | <b>Dépenses }
  .
  {Estimation des dépenses totales (Devise) : {+"           " } | {Coût total calculé  {<color:blue> 354.0} Devise }}
  -- | --
  <b>Détail des dépenses
  ..
  .
  {
    {/ <b>Fluides de fonctionnement | Frais annexes | Glace utilisée | Appâts }
  .
    {
    .                   | {Volume (L)} | {Prix (Devise/L)} | {Prix total (Devise)}
    { ^Carburant^ }     | { {+"           " } } | { {+"           " } } | { {+"           " } }
    huile de moteur :   | { {+"           " } } | { {+"           " } } | { {+"           " } }
    huile hydraulique : | { {+"           " } } | { {+"           " } } | { {+"           " } }
    }
  }
  .
  -- | --
  .
    {/ Fluides de fonctionnement | <b>Frais annexes | Glace utilisée | Appâts }
   {
    Frais de débarquement | {+"           " } | Devise
    Alimentation          | {+"           " } | Devise
    Perte d'engin         | {+"           " } | Devise
    Autre                 | {+"           " } | Devise
    .
    Commentaires              | { "commentaires       "}
  }
  .
  -- | --
  .
    {/ Fluides de fonctionnement | Frais annexes | <b>Glace utilisée | Appâts }
    .
  {
    Quantité de glace | {+"           " }  | ^Unité (au kg ou par sac)^
    Coût de la glace | {+"           " }  | Devise
  }
  .
  -- | --
  .
    {/ Fluides de fonctionnement | Frais annexes | Glace utilisée | <b>Appâts }
    .
   {
    { ^Type d'appât^ } | Nombre d'appâts {+"           " } | ^Unité de conditionnement^
    . | Coût des appâts | {+"           " } | Devise
    {[<&plus>] }
  }
  .
  -- | --
  {{[Fermer et retour à l'observation] | [Enregistrer]}}
}
@endsalt
