@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture    | <i><color:blue>[8]
       ++ Partie retenue       | <i><color:blue>[8]
       ++ Partie non retenue, Vrac | <color:black>[0]
       +++ Détaillé | <color:black>[0]
       +++ Non détaillé | <color:black>[0]
       ++ Partie non retenue, Hors-Vrac | <color:black>[0]
       +++ Animaux | <color:black>[0]
       +++ Ecosystèmes Marins Vulnérables | <color:black>[0]
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [<b>Partie non retenue, Hors Vrac] | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] } }
    }
  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

