@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + <back:#DDF>Capture
       ++ Partie retenue
       +++ Consommation humaine | <i><color:blue>[1]
       +++ Obligation à débarquer| <i><color:blue>[2]
       +++ Appat | <i><color:blue>[1]
       +++ Godaille | <i><color:blue>[1]
       ++ Partie non retenue, Vrac
       ++ Partie non retenue, Hors-Vrac
   }
    .
    .
    .
   --
   {
      [Contrôler la saisie] | [ <b><< ]
   }
  } | . | {
    { [<b>Capture] | / | [...] | . | . | . | . | . | . | . | . | . | . | . | . | . | . | [<&chevron-left>] | [<&chevron-right>] }

    {[ ] Coup nul ? }
    {Capture Totale (kg) : | " <i><color:blue>Poids total capture (kg) " }

  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

