@startsalt
{
  {/ Détails | <b> Capture }
  {+
    {T
         + <back:#DDD>Capture         | <i><color:blue>[200kg]
         ++ Partie retenue       | [100kg] (1/2)
       +++ Consommation humaine | <i><color:blue>[75kg]
       +++ Industrie | <i><color:blue>[25kg]
         ++ Partie rejetée, Vrac      | [10kg]
         ++ Partie rejetée, Hors-Vrac | [5kg]
    }
    .
    .
    .
    .
    --
    {
       [<&checkmark> Contrôler] | [ << ]
    }
  } | . | {

   { [<b>Capture] | / | [...]}

       {[ ] Coup nul ? }
       {Capture (toutes espèces) (kg) : | " <i><color:blue>200" }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

