@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture
       ++ Partie retenue
       ++ Partie non retenue, Vrac
       +++ Détaillé
       +++ Non détaillé | <color:black>[0]
       ++ Partie non retenue, Hors-Vrac
       +++ <back:#DDD>Animaux | <i><color:blue>[2]
       +++ Ecosystèmes Marins Vulnérables | <color:black>[0]
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [Partie non retenue, Vrac] | [Détaillé] | [<b>Animaux] | (2) | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] } }

    { [ ] Inventaire exhaustif des espèces ? }
    ---
    {#
          . | {[ <&plus> ] | [ <&trash> ] }  | . | . | . | . | .
          # | <b>Espèce commerciale  | <b>Poids total (kg)     |  <b>Nb indiv. total  | <b>Coef. échant. | <b>Poids. échant. | <b>Nb indiv échant. | <&menu>
          1 | ^MNZ- Baudroie   ^ |  50   |  24   |   10          | 4 | 10 | <&bar-chart> <&comment-square> <&image>
          2 | ^CTC - Seiche commune   ^ |  20   |  36   |   10          | 4 | 10 | <&bar-chart> <&comment-square> <&image>
        }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

