@startsalt
{
  {/ Détails | <b> Capture }
  {+
    {T
         + <back:#DDD>Capture
         ++ Partie retenue
         ++ Partie non retenue, Vrac
         ++ Partie non retenue, Hors-Vrac
    }
    .
    .
    .
    .
    --
    {
       [<&checkmark> Contrôler] | [ <b><< ]
    }
  } | . | {

   { [<b>Capture] | / | [...] | | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] }
    . | . | {* ...
    ... | Partie retenue | Partie non retenue, Vrac | Partie non retenue, Hors-Vrac }
    }
       {[X] Coup nul ? }
       {Capture (toutes espèces) (kg) : | " 0" }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

