@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture    | <i><color:blue>[8]
       ++ Partie retenue       | <i><color:blue>[8]
       +++ Appart | <i><color:blue>[1]
       +++ <back:#DDF>Consommation humaine | <i><color:blue>[2]
       +++ Godaille | <i><color:blue>[1]
       +++ Industrie | <i><color:blue>[2]
       +++ Obligation à débarquer| <i><color:blue>[2]
       ++ Partie non retenue, Vrac | <color:gray>[0]
       ++ Partie non retenue, Hors-Vrac | <color:gray>[0]
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [Partie retenue] | [<b>Consommation humaine] | (2) | . | . | . | . | . | . | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] } }

    {Poids total (kg)* : | " 0    " | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |[ ] Estimé ?}

    {Coef. éch. : | " 1/1    " | . | . | . | . | . | Poids échant. (kg)* : | " 0    " }

    { [ ] Inventaire exhaustif des espèces ? }
    ---
    {#
          . | {[ <&plus> ] | [ <&trash> ] }  | . | . | . | . | .
          # | <&arrow-thick-top> <b>Espèce commerciale  | <b>Présentation | <b>État | <b>Poids total (kg)     |  <b>Taux échant  | <b>Poids échant. | <b>Nb indiv échant. | <&menu>
          1 | ^MNZ- Baudroie       ^ | ^ Entier   ^ | ^ Frais ^ | 50   |  .   |   10          | 4 | <&bar-chart>
          2 | ^BSS - Bar européen       ^ | ^ Eviscéré ^ | ^ Frais ^ | 50   |  .   |   10          | 4 | <&bar-chart>
        }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

