@startsalt
{
  {/ Détails | <b> Capture }
  {+
    {T
         + <back:#DDD>Capture         | [200kg]
         ++ Partie retenue, Vrac      | [100kg] (1/2)
         ++ Partie rejetée, Vrac      | [10kg]
         ++ Partie rejetée, Hors-Vrac | [5kg]
    }
    .
    <i><color:orange>ou bien sous forme dépliée : (à confirmer)
    .
    {T
         + <back:#DDD>Capture           | [200kg]
         ++ Partie retenue, Vrac        | [100kg] (1/2)
         ++ <color:#666>Partie rejetée  | <color:#666>[15kg]
         +++ Vrac                       | [10kg]
         +++ Hors-Vrac                  | [5kg]
    }
    .
    .
    .
    --
    {
       [<&checkmark> Contrôler] | [ << ]
    }
  } | . | {

   { [<b>Capture] | / | [...]}

       {Capture (toutes espèces) (kg) (*): | " 200" }
       <i><color:orange> -> Est-ce obligatoire ?
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

