@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture
       ++ Partie retenue
       +++ Appat | <i><color:blue>[1]
       +++ <back:#DDD>Consommation humaine | <i><color:blue>[2]
       +++ Godaille | <i><color:blue>[1]
       +++ Obligation à débarquer | <i><color:blue>[2]
       ++ Partie non retenue, Vrac
       ++ Partie non retenue, Hors-Vrac
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [Partie retenue] | [<b>Consommation humaine] | (2) | . | . | . | . | . | . | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] } }

    {Poids total (kg)* : | " 0    " | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |. |[ ] Estimé ?}

    {Coef. éch. : | " 1/1    " | . | . | . | . | . | Poids échant. (kg)* : | " 0    " }

    { [ ] Inventaire exhaustif des espèces ? }
    ---
    {#
          . | {[ <&plus> ] | [ <&trash> ] }  | . | . | . | . | .
          # | <&arrow-thick-top> <b>Espèce commerciale  | <b>Présentation | <b>État | <b>Catégorie | <b>Poids total (kg)     |  <b>Taux échant  | <b>Poids échant. | <b>Nb indiv échant. | <&menu>
          1 | ^MNZ- Baudroie       ^ | ^ Entier   ^ | ^ Frais ^ | ^Moyen^ | { "50" | [ ] Estimé ? } |  .   |   { "10" | [ ] Estimé ? }          | "4" | <&bar-chart> <&comment-square> <&image>
          2 | ^BSS - Bar européen       ^ | ^ Eviscéré ^ | ^ Frais ^ | ^Petit^ | { "50" | [ ] Estimé ? }  |  .   |   { "10" | [ ] Estimé ? }          | "4" | <&bar-chart> <&comment-square> <&image>
        }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

