@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture    | .
       ++ Partie retenue       | <i><color:blue>[8]
       +++ Appart | <i><color:blue>[1]
       +++ <back:#DDF>Consommation humaine | <i><color:blue>[2]
       +++ Godaille | <i><color:blue>[1]
       +++ Industrie | <i><color:blue>[2]
       +++ Obligation à débarquer| <i><color:blue>[2]
       ++ Partie non retenue, Vrac | <color:gray>[0]
       ++ Partie non retenue, Hors-Vrac | <color:gray>[0]
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ << ]
   }
  } | . | {
    { [Capture] | / | [Partie retenue] | [<b>Consommation humaine] }

    {Poids total (kg) : | "     " }

    {Taux échant (1/n) : | "     " | Poids échant (kg) : | "     " }

    { [ ] Inventaire exhaustif des espèces ? }

    {#
          . | {[ <&plus> ] | [ <&trash> ] }  | . | . | . | . | .
          # | <b>Espèce commerciale  | <b>Présentation | <b>État | <b>Poids total (kg)     |  <b>Taux échant  | <b>Poids échant. | <b>Nb indiv échant.
          1 | ^MNZ- Baudroie       ^ | ^     WHL ^ | ^ FRE ^ | 50   |  .   |   10          | 4
          2 | ^MNZ- Baudroie       ^ | ^     GUT ^ | ^ FRE ^ | 50   |  .   |   10          | 4
        }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

