@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture    | .
       ++ <back:#DDF>Partie retenue       | <i><color:blue>[8]
       +++ Appat | <i><color:blue>[1]
       +++ Consommation humaine | <i><color:blue>[2]
       +++ Godaille | <i><color:blue>[2]
       +++ Industrie | <i><color:blue>[1]
       +++ Obligation à débarquer| <i><color:blue>[2]
       ++ Partie non retenue, Vrac | <color:gray>[0]
       ++ Partie non retenue, Hors-Vrac | <color:gray>[0]
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [<b>Partie retenue] | [...] }

    <i><color:blue>Rien à afficher sur cet écran
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

