@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + <back:#DDF>Capture    | .
       ++ Partie retenue       | <i><color:blue>[6]
       +++ Appat | <i><color:blue>[1]
       +++ Consommation humaine | <i><color:blue>[1]
       +++ Godaille | <i><color:blue>[1]
       +++ Industrie | <i><color:blue>[1]
       +++ Obligation à débarquer| <i><color:blue>[2]
       ++ Partie non retenue, Vrac | <i><color:gray>[0]
       ++ Partie non retenue, Hors-Vrac | <i><color:gray>[0]
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ << ]
   }
  } | . | {
    { [<b>Capture] | / | [...]}

    {[ ] Coup nul ? }
    {Capture (toutes espèces) (kg) : | " <color:gray>Poids total capture (kg) " }

  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

