@startsalt
{
  {/ Détails | <b> Capture }
  {+
    {T
         + <back:#DDD>Capture         | <i><color:blue>[200kg]
         ++ Partie retenue       | [185kg] (1/2)
       +++ Appat | <i><color:blue>[10kg]
       +++ Consommation humaine | <i><color:blue>[40kg]
       +++ Godaille | <i><color:blue>[10kg]
       +++ Industrie | <i><color:blue>[75kg]
       +++ Obligation à débarquer| <i><color:blue>[50kg]
         ++ Partie non retenue, Vrac      | [10kg]
         ++ Partie non retenue, Hors-Vrac | [5kg]
    }
    .
    .
    .
    .
    --
    {
       [<&checkmark> Contrôler] | [ <b><< ]
    }
  } | . | {

   { [<b>Capture] | / | [...]| . | . | . | . | . | . | . | . | . | [<&chevron-left>] | [<&chevron-right>] }

       {[ ] Coup nul ? }
       {Capture (toutes espèces) (kg) : | " <i><color:blue>200" }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

