@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture
       ++ Partie retenue
       ++ Partie non retenue, Vrac
       +++ Détaillé
       ++++ Animaux | <color:black>[0]
       ++++ Ecosystèmes Marins Vulnérables | <color:black>[0]
       +++ Non détaillé | <color:black>[0]
       ++ Partie non retenue, Hors-Vrac
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [<b>Partie non retenue, Vrac] | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] } }
    }
  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

