@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture
       ++ Partie retenue
       ++ Partie non retenue, Vrac
       +++ Détaillé
       +++ Non détaillé | <color:black>[0]
       ++ Partie non retenue, Hors-Vrac
       +++ <back:#DDD>Animaux | <i><color:blue>[2]
       +++ Ecosystèmes Marins Vulnérables | <color:black>[0]
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [Partie non retenue, Hors Vrac] | [Détaillé] | [<b>Animaux] | (2) | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] } }
    ---
      {Poids total (kg) : | "  <i><color:blue>26   " }
    ---
    {#
          <&arrow-thick-top> | *  | {[ <&plus> ] | [ <&trash> ] | [ ] Estimé ? } | * | * | *
          [ ] | Etat | # | <b>Espèce scientifique  | <b>Poids total (kg)     |  <b>Nb indiv. total | <&menu>
          [ ] | <&pencil> | 1 | ^TOR - Torpille  ^ |  12   |  5   | <&bar-chart> <&comment-square> <&image>
          [ ] | <&pencil> | 2 | ^CON - Congar ^ |  7   |  3   |   | <&bar-chart> <&comment-square> <&image>
        }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

