@startsalt
{
  {/ Détails | <b> Capture }
  {+
    {T
         + <back:#DDD>Capture
         ++ <color:grey>Partie retenue
         ++ <color:grey>Partie non retenue, Vrac
         ++ <color:grey>Partie non retenue, Hors-Vrac
    }
    .
    .
    .
    .
    --
    {
       [<color:grey>Contrôler la saisie] | [ <b><< ]
    }
  } | . | {

   { [<b>Capture] | / | [...] | . | . | . | . | . | . | . | . | [<&chevron-left>] | [<&chevron-right>] }

       {[X] Coup nul ? }
       {Capture (toutes espèces) (kg) : | " " }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

