@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture
       ++ Partie retenue
       ++ Partie non retenue, Vrac
       +++ Détaillé
       +++ Non détaillé | <color:black>[0]
       ++ Partie non retenue, Hors-Vrac
       +++ Animaux | <color:black>[0]
       +++ <back:#DDD>Ecosystèmes Marins Vulnérables | <i><color:blue>[1]
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [Partie non retenue, Vrac] | [Détaillé] | [<b>Ecosystèmes Marins Vulnérables] | (1) | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] } }
    .
    {Poids total (kg) : | "  <i><color:blue>10   " }
    .
    --
    {#
          <&arrow-thick-top> | *  | {[ <&plus> ] | [ <&trash> ] | [ ] Estimé ? } | * | * | * | * | * | * | * | *
          [ ] | # | <b>Catégorie d'EMV  | <b>Poids total (kg)     |   <&menu>
          [ ] | 1 | ^BC - Coraux noirs      ^ |  10    | <&comment-square> <&image>
        }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

