@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture
       ++ Partie retenue
       ++ Partie non retenue, Vrac
       +++ Détaillé
       +++ Non détaillé | <color:black>[0]
       ++ Partie non retenue, Hors-Vrac
       +++ <back:#DDD>Animaux | <i><color:blue>[2]
       +++ Ecosystèmes Marins Vulnérables | <color:black>[0]
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [Partie non retenue, Vrac] | [Détaillé] | [<b>Animaux] | (2) | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] } }
    ---
      {Poids total (kg) : | "  <i><color:blue>70   " | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | [ ] Estimé ? }
  .
  {[ <&plus> ] | [ <&trash> ] }

    {#

          [ ] | # | <b>Espèce scientifique  | <b>Poids total (kg)     |  <b>Nb indiv. total   | <&menu>
          [ ] | 1 | ^MON - Lophius piscatoruis  ^ |  50   |  24    | <&bar-chart> <&comment-square> <&image>
          [ ] | 2 | ^ANK - Lophius budegassa  ^ |  20   |  36   |    <&bar-chart> <&comment-square> <&image>
        }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

