<@startsalt
{
  {+
    { | . |  <b>Ajouter des mesures :  | . }
    --
    { | . | Espèce scientifique   | . }
    { | . | <color:grey>Lophius piscatorius   | .  }
    .
    { | . | Longueur totale (cm) * | .  }
    { | . | "   12  "  }
    .
    { [Ajouter] }
    }
 }
@endsalt

