@startsalt
{
  {/ Détails | <b> Capture }
  {+
   {T
       + Capture
       ++ Partie retenue
       ++ Partie non retenue, Vrac
       +++ Détaillé
       ++++ <back:#DDD>Animaux
       ++++ Ecosystèmes Marins Vulnérables | <i><color:blue>[1]
       +++ Non détaillé | <color:black>[0]
       ++ Partie non retenue, Hors-Vrac
   }
    .
    .
    .
   --
   {
      [<&checkmark> Contrôler] | [ <b><< ]
   }
  } | . | {
    { [Capture] | / | [Partie non retenue, Vrac] | [Détaillé] | [<b>Animaux] | (2) | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | . | { [<&chevron-left>] | [<&chevron-right>] } }
      {Poids total (kg) : | "  <i><color:blue>19   " }
      { [ ] Inventaire exhaustif des espèces ? }
    ---
    {#
          <&arrow-thick-top> | *  | {[ <&plus> ] | [ <&trash> ] | [ ] Estimé ? } | * | * | *
          [ ] | # | <b>Espèce scientifique  | <b>Poids total (kg)     |  <b>Nb indiv. total | <&menu>
          [ ] | 1 | ^TOR - Torpille  ^ |  12   |  5   | <&bar-chart> <&comment-square> <&image>
          [ ] | 2 | ^CON - Congar ^ |  7   |  3   |   | <&bar-chart> <&comment-square> <&image>
        }
  }

  -- | -- | --
  { [Fermer] | [Sauvegarder] }
}
@endsalt

