@startsalt
{

  {/  Détails | Capture | <b> Captures accidentelles (1) }
  {/  Mesures individuelles | <b>Remise à l'eau (1) }

    { [ <&plus> ] | [<&trash>] }
	{#
      [ ] | # | <&arrow-thick-top> <b>Référence de la marque | <b>Date de remise à l'eau     | <b>Latitude   | <b>Longitude | <&menu>
      [ ] | 1 | Zzz | 12/02/2024 12:53          | 43°9.354' N | 4°21.996'E | <&comment-square>
    }
  --

  {
    [Fermer] | [Sauvegarder]
  }
}
@endsalt
