@startuml
hide empty members

  class ExpertiseArea {
    + id : integer
    + label : string
    + name : string
    + description: string [0..1]
    + creationDate : Date
    + updateDate : timestamp
  }

  note right of ExpertiseArea: Zone de compétence\nExemple: Guyane, La Réunion, Mayotte, etc.

  class ExpertiseArea2Location

  note left: Lieux de la zone\n(terrestre et en mer)

  class ExpertiseArea2LocationLevel

  note right: Niveaux de lieux de la zone\n(terrestre et en mer)

  package referential #DDDDDD {

    class Status

    object AnyReferentialItem

    package location {
      class LocationClassification
      class Location
      class LocationLevel

      LocationClassification "1" <-right- "*" Location
      LocationLevel "1" <-left- "*" Location

    }

    note bottom of LocationClassification: Permet de distinguer\nlieux terrestres et en mer.

    package spatial {
      class SpatialItemType {
        id: integer
        label: string
        name: string
        objectType: ObjectType
      }

      class SpatialItem2Location
      class SpatialItem {
        objectId: integer
      }


      SpatialItem2Location "0..*" -up-> "1" SpatialItemType
      SpatialItem2Location "0..*" --> "1" SpatialItem

      SpatialItem --> AnyReferentialItem
    }
  }

  ExpertiseArea "*" --> "1" Status
  ExpertiseArea "1" *-- "0..*" ExpertiseArea2Location: locations
  ExpertiseArea2Location "0..*" --> "1" Location
  ExpertiseArea "1" *-- "0..*" ExpertiseArea2LocationLevel: locationLevels
  ExpertiseArea2LocationLevel "0..*" --> "1" LocationLevel

  SpatialItem2Location "0..*" -up-> "1" Location

}

@enduml
