@startsalt
{
  <b>Nouveau navire
  ..

  .

  { "Type de navire*       "}
  { "Nom du navire*        "} | { "Immatriculation*   "}
  Date validité début:  | { ^01/02/2019^ }
  <&map-marker> Base port*:     | { ^MA - Mahé Island^ }
  { "Status*       "}

  .
  Commentaires              | { "commentaires       "}
  .
  -- | --
  | {[Annuler] | [Ajouter]}
}
@endsalt
