@startsalt
{
  <b>Nouvelle observation
  ..
  {/ <b>General | Navires observés }
  .
  Programme de collecte*:    | { ^SIH-OBSDEB^ }
  Lieu d'observation*:       | { ^MA - Mahé Island^ }
  Date/Heure début*:         | { ^01/02/2019^ | ^09:55^ }
  Date/Heure fin:            | { ^01/02/2019^ | ^09:55^ }
  Observateurs*:             | { ^Observateur #1^ | [<&plus>] | [<&x>]}
  Autres caractéristiques:   | { Paramètre 1 (ex: Nombre d'homme à bord) : | "   1  " }
  .                          | { Paramètre 2 : | ^Valeur qualitative^ }

  .
  Commentaires               | { "commentaires       "}

  -- | --

  .                          | {[Annuler] | [Sauvegarder]}
}
@endsalt
