@startsalt
{
  <b>Nouvelle observation
  ..
  {/ General | <b>Navires observés }
  .
  {[<&plus>]  | [<&trash>] | [<&magnifying-glass>] | [Montrer les navires observés les 12 derniers mois]}

  {#
  # | <b>Type de navire  | <b>Nom     | <b>Immatriculation | <b>Date/Heure validité début     | <b> Base port          | <b>Status
  1 | Mini Mahe          | Ti Pikir   | SZ178              | 02/15/2019 11:01                 |  LS-LRT - La retraite  | au port
  2 | Pirogue            | Saint Rock | SZ616              | 02/15/2019 15:05                 |  LS-PC - Pointe Conan  | en mer
  }

  -- | --

  . | {[Annuler] | [Sauvegarder]}
}
@endsalt
