@startmindmap
* Tickets OTRS Opus Activité
** <&circle-x> Bugs applicatifs (**41 %**)
** <&wifi> Problèmes réseaux (WAF, maintenance, lenteur) (**14 %**)
** <&person> Problèmes d'utilisation (**13 %**)
** <&globe> Enrichissement régionalisation (**10 %**)
** <&key> Droits QIM et Navires (**14 %**)
** <&trash> Absence de données (**4 %**)
** <&dollar> Propositions d'améliorations (**4 %**)
@endmindmap