@startgantt
hide footbox

<style>
ganttDiagram {
    unstartedTask {
        FontName Helvetica
        FontColor Black
        FontSize 12
        FontStyle bold
        BackGroundColor DeepSkyBlue
        LineColor DeepSkyBlue
    }
    task {
        FontName Helvetica
        FontColor Black
        FontSize 12
        FontStyle bold
        BackGroundColor DeepSkyBlue
        LineColor DeepSkyBlue
    }
    milestone {
        FontColor black
        FontSize 12
        FontStyle bold
        BackGroundColor yellow
        LineColor FireBrick
    }
    note {
        FontColor DarkGreen
        FontSize 10
        LineColor OrangeRed
    }
    arrow {
        FontName Helvetica
        FontColor red
        FontSize 18
        FontStyle bold
        BackGroundColor GreenYellow
        LineColor blue
        LineStyle 8.0;13.0
        LineThickness 3.0
    }
    separator {
        BackgroundColor OliveDrab
        LineStyle 8.0;3.0
        LineColor Gray
        LineThickness 1.0
        FontSize 16
        FontStyle bold
        FontColor White
        Margin 5
        Padding 6
    }
    timeline {
        BackgroundColor Snow
    }
    closed {
        BackgroundColor pink
        FontColor red
    }
}
</style>

printscale weekly
projectscale weekly

title Calendrier d'activité - Development

today is colored in forestGreen

Project starts the 2024/04/08

[r2.9.17] as [TASK1] requires 3 weeks
[TASK1] is colored in grey

[Testing1] requires 1 week
[TASK1]->[Testing1]


[r2.9.18] as [TASK2] requires 4 weeks
[TASK2] is colored in Grey
[TASK1]->[TASK2]
[Testing2] requires 1 week
[TASK2]->[Testing2]
[Demo MOA 1] happens 11 day after [Testing2]'s end

[pre-prod] as [PREPROD] requires 2 week and starts the 6th of May 2024
[PREPROD] is colored in salmon

[r2.9.19.2] as [TASK3] requires 4 weeks
[TASK3] is colored in grey
[TASK2]->[TASK3]
[Testing3] requires 1 week and starts the 1th of July 2024
[TASK3]->[Testing3]
[Demo MOA 2] happens 9th of July 2024

[r2.9.20] as [TASK4] requires 4 weeks
[TASK4] is colored in grey
[TASK3]->[TASK4]
[Testing4] requires 1 week and starts the 2th of August 2024
[TASK4]->[Testing4]


[r2.9.21] as [TASK5] requires 4 weeks
[TASK5] is colored in grey
[TASK4]->[TASK5]
[Testing5] requires 1 week and starts the 2th of September 2024
[TASK5]->[Testing5]
[Demo MOA 3] happens 27th of August 2024

[r2.9.22] as [TASK6] requires 4 weeks and starts the 5th of August 2024
[TASK6] is colored in green
[TASK5]->[TASK6]
[Testing6] requires 1 week
[TASK6]->[Testing6]
[Demo MOA 4] happens 3 day after [Testing6]'s end

[r2.9.23] as [TASK7] requires 3 weeks and starts the 2th of September 2024
[TASK7] is colored in Lavender/LightBlue
[TASK6]->[TASK7]
[TASK7]->[Testing7]
[Testing7] requires 1 week and starts the 22th of September 2024
[Demo MOA 5] happens 2 day after [Testing7]'s end

[validation] as [VAL] requires 2 week and starts the 1th of October 2024
[VAL] is colored in orange
[Testing7]->[VAL]

[r2.9.23.x fix] as [TASK8] requires 3 weeks and starts the 2th of September 2024
[TASK8] is colored in Lavender/LightBlue
[TASK7]->[TASK8]

[Production] as [PROD] requires 1 week and starts the 25th of October 2024
[PROD] is colored in green
[VAL]->[PROD]

[GPR] as [CONG_GPR] requires 4 week and starts the 19th of July 2024
[VFA] as [CONG_VFA] requires 3 week and starts the 15th of August 2024
[CDE] as [CONG_CDE] requires 11 days and starts the 5th of september 2024
[GPR] is colored in lightgrey
[VFA] is colored in lightgrey
[CDE] is colored in lightgrey

[ELR] as [CONG_ELR] requires 4 week and starts the 15 of July 2024
[ELR] is colored in lightsteelblue

[JLT] as [CONG_JLT] requires 2 week and starts the 12 of August 2024
[JLT] is colored in lightsteelblue

[JVF] as [CONG_JVF] requires 2 week and starts the 29th of July 2024
[JVF] is colored in plum

[MFA] as [CONG_MFA] requires 2 week and starts the 09th of October 2024
[MFA] is colored in plum

[BLE] as [CONG_BLE] requires 3 week and starts the 5th of August 2024
[BLE] is colored in plum

[MDE] as [CONG_MDE] requires 3 week and starts the 8th of July 2024
[MDE] is colored in plum

[CGFS 2 VFA] as [EMB] requires 3 week and starts the 31th of September 2024
[EMB] is colored in lightgrey

skinparam legendBackgroundColor with

legend
  |<#lightgrey>  | Congés/Abs. MOE |
  |<#lightsteelblue>  | Congés MOA |
  |<#plum>   | Congés Dev |
end legend

@endgantt
