@startsalt
{
  <b>La Ciotat</b> - 08/02/2022 - <b>MAC - Maquereau commun
  --
  {/  Détails | <b>Lots - 123456 Navire 1 | Lots - 7891234 Navire 2}
  ..
  { <&plus> <&trash> <&chevron-bottom> }

  {#
     # | <b>Espèce commerciale |  <b>Catégorie de tri terrain | <b>Catégorie UE | <b>Etat | <b>Présentation  | <b>Poids total (kg)| <b>Nb ind. total | <b>Identification à confirmer ?| <&menu>
     [ ] . | MAC - Maquereau commun | 20 | Cat UE20 | FRE - Frais | WHL - Entier | 1 | 2 | [ ]. | <&bar-chart> <&comment-square> <&image>
     [X] . | MAC - Maquereau commun | 30 | Cat UE30 | FRE - Frais | WHL - Entier | 1 | 3 | [X]. | <&bar-chart> <&comment-square> <&image>
   }

}
@endsalt