@startsalt
{

  {<b>Calendriers d'activité                                                                                                                                                                                                       <&reload>}
   --

    {
        Programme de collecte : | . | ^ SIH-ACTIFLOT         ^
        .
        Lieu d'immatriculation : | . | ^ MA - Marseille       ^ | . | . | Port d'exploitation : | . | ^JMA - La Madrague de Montredon^
        .
        Navire : | . | ^ 123456 - SONNY       ^ | . | . | Etat : | . | ^En cours de saisie            ^
        .
        Objectif d'enquête directe ? :   | . |{ (X) <b>Oui | () Non}|  . | . | Enquête éco ? :   | . | { () Oui | (X) <b>Non}
        .
        Organisme saisisseur :   | . |^ Ifremer              ^ |  . | . | Saisisseur :   | . | ^ Nicolas DUPOND               ^

    }

  --
  {2 résultats  {}[<&caret-bottom>] | [Fermer] | [Appliquer]}}
}
@endsalt
