@startsalt
{
	{#
     . | . | <b> Stratégie | * | * | * | <b> Calendrier d'activité | * | * | * | *
     . | <b> Connexion | <b> Consultation | <b> Création |<b> Modification | <b> Suppression | <b> Consultation | <b> Création | <b> Modification | <b> Suppression | <b> Validaion
     Administrateur de référentiel | Oui | Oui | Oui | Oui | Oui | Oui | Oui | Oui(2) | Oui(2) | Non
     Responsable de programme | Oui | Oui | Oui | Oui | Oui | Oui | Oui | Oui(2) | Oui(2) | Oui
     Observateur | Oui | Non | Non | Non | Non | Oui(1) | Oui | Oui(1)(2) | Oui(1)(2) | Non


    }
}
@endsalt