@startuml
'https://plantuml.com/class-diagram

class ACTIVITY_CALENDAR {
+ID
+YEAR
+DIRECT_SURVEY_INVESTIGATION
+COMMENTS
+CREATION_DATE
+UPDATE_DATE
+RECORDER_PERSON_FK
+VESSEL_FK
+PROGRAM_FK
+RECORDER_DEPARTMENT_FK
}

class SURVEY_MEASUREMENT {
+ID
+PMFM_FK
+QUALITATIVE_VALUE_FK
+ACTIVITY_CALENDAR_FK
}

class VESSEL_USE_FEATURES {
+ID
+START_DATE
+END_DATE
+CREATION_DATE
+UPDATE_DATE
+VESSEL_FK
+PROGRAM_FK
+IS_ACTIVE
+ACTIVITY_CALENDAR_FK
+BASE_PORT_LOCATION_FK
}

class VESSEL_USE_MEASUREMENT {
+ID
+NUMERICAL_VALUE
+PMFM_FK
+VESSEL_USE_FEATURES_FK
}

class GEAR_USE_FEATURES {
+ID
+START_DATE
+END_DATE
+CREATION_DATE
+UPDATE_DATE
+VESSEL_FK
+PROGRAM_FK
+GEAR_FK
+ACTIVITY_CALENDAR_FK
+METIER_FK
}

class FISHING_AREA {
+ID
+NEARBY_SPECIFIC_AREA_FK
+DEPTH_GRADIENT_FK
+DISTANCE_TO_COAST_GRADIENT_FK
+LOCATION_FK
+GEAR_USE_FEATURES_FK
}

class GEAR_PHYSICAL_FEATURES {
+ID
+START_DATE
+END_DATE
+CREATION_DATE
+UPDATE_DATE
+VESSEL_FK
+PROGRAM_FK
+GEAR_FK
+ACTIVITY_CALENDAR_FK
+METIER_FK
}

class GEAR_PHYSICAL_MEASUREMENT {
+ID
+NUMERICAL_VALUE
+PMFM_FK
+GEAR_PHYSICAL_FEATURES_FK
}


ACTIVITY_CALENDAR "1" *-up- "4?..6" SURVEY_MEASUREMENT: "     "
ACTIVITY_CALENDAR "1" *-right- "0..*" GEAR_USE_FEATURES: "     "
ACTIVITY_CALENDAR "1" *-down- "0..12" VESSEL_USE_FEATURES: "     "
ACTIVITY_CALENDAR "1" *-left- "0..*" GEAR_PHYSICAL_FEATURES: "     "
VESSEL_USE_FEATURES "1" *-right- "0..3" VESSEL_USE_MEASUREMENT: "     "
GEAR_USE_FEATURES "1" *-right-* "1..2" FISHING_AREA: "     "
GEAR_PHYSICAL_FEATURES "1" *-left-* "0..*" GEAR_PHYSICAL_MEASUREMENT: "     "



@enduml