@startsalt
{
  Navire : <b>SONNY - 123456 - MA - 7,81 m - 2022
  --
  {/ <b>Général | Navires | Calendrier | Métiers | Zones d'activité}
  ..
  .
  {{
    Objectif d'enquête directe ?* | { (X) <b>Oui | () Non | . | Qualification de l'enquête* : | ^Indirecte^}
    Enquête éco ?* | { (X) <b>Oui | () Non }} |
  }
  .
  {
  <b>Caractéristiques de l'enquête
     {

     . | Fiabilité de l'enquête* : | ^Fiable   ^
     . | Inactivité annuelle confirmée par l'observateur* : | { (X) <b>Oui | () Non }
     . | Le professionnel accepterait-il de répondre à une autre enquête ?* : | { () Oui | (X) <b>Non }
     . | Métiers déclarés dans les journeaux de bord/fiches de pêche : | ^         ^
     . | Habitudes de vente à la criée : | ^         ^
     }
  } . {+
                           {
                           <font color=grey size=10>Stratégie
                           ACTIFLOT démarrage le 01/01/2019
                           --
                           <font color=grey size=10>Saisisseur
                           Obs1
                           <font color=grey size=10>Groupe EI
                           --
                           <font color=grey size=10><&calendar>Créé le 20/03/2023 17:08:31
                           <font color=grey size=10><&clock>Mis à jour le 20/03/2023 17:08:31
                           .
                           <font color=grey size=10>Mode saisie <b>bureau
                           .
                           [ Terminer la saisie]
                           }}
    <b>Commentaires :
         {+ 19.01.2017 : Appel sans réponse
            08/03/2019 : Conversation téléphonique
            2020 : Sort souvent avec Jean (BIBAS) --> Pêchent également sur ensemble sur BIBAS
            de temps en temps à ERU
            12/02/2022 : Hélice cassée fin 2022
            .
            .
            .
            .
            .
         }
  .
  --
  { [Fermer] | [Sauvegarder] }
}
@endsalt