@startsalt
{
	{#
     . | . | <b> Calendrier d'activité | * | * | * | *
     <b>Profil utilisateur | <b>Privilège de programme | <b> Consultation | <b> Création | <b> Modification | <b> Suppression | <b> Validation
     Administrateur de référentiels | . | Oui | Oui | Oui(2) | Oui(2) | Non
     . | Responsable de programme | Oui | Oui | Oui(2) | Oui(2) | Oui
     Superviseur | ? | Oui(1) | Oui | Oui(1)(2) | Oui(1)(2) | Non
     Observateur | Observateur  | Oui(1) | Oui | Oui(1)(2) | Oui(1)(2) | Non
    }
}
@endsalt