@startsalt
{
  Navire : <b>LIEU IMMAT - 123456 - VESSEL1 - Activité 2022
  --
  {/ <b><&info>Général | Navire | <&calendar>Calendrier | <b><&cog>Métiers (2)) | <font color=grey>Carte}

  ..
  {# . | # |Métier | {<b>Maillage de l'engin (logbook) (mm)
                engin -
                inconnue -
                Déclaration d'un professionnel} |
              {<b>Maillage étiré de l'engin (mm)
                engin -
                plus petite maille -
                Déclaration d'un professionnel} |
              {<b>Maillage étiré de l'engin (mm)
                engin -
                plus grande maille -
                Déclaration d'un professionnel} |
              {<b>Longueur levée (m)
                engin -
                totale -
                Déclaration d'un professionnel}
     [ ]. | 0 | GTRMZZ - Trémails à poissons | 100 | 97 | 103 | .
     [ ]. | 1 | GTRNEP - Trémails à langoustines | . | 57 | . | 100
  }

  { [Fermer] | [<&reload> Réinitialiser] | [Sauvegarder] }
}
@endsalt