@startsalt
{
  Navire : <b>LIEU IMMAT - 123456 - VESSEL1 - Activité 2022
  --
  {/ <b><&info>Général | Navire | <&calendar>Calendrier | <&cog>Métiers | <font color=grey>Carte}
  ..
  .
  {{
    <font color=grey>Objectif d'enquête directe ?* | { (X) <font color=grey><b>Oui | () <font color=grey>Non }
    Enquête éco ?* | { (X) <b>Oui | () Non }} |
  }
  .
    <b>Observateur(s)
       {
       . | ^Observateur1 ^ | . |  . | . | . | . | . | <&plus> <&x>
       }
  .
  {
  <b>Caractéristiques de l'enquête
     {
     . | Qualification de l'enquête* : | ^Directe  ^
     . | Fiabilité de l'enquête* : | ^Fiable   ^
     . | Inactivité annuelle confirmée par l'observateur : | { () Oui | (X) <b>Non }
     . | Le professionnel accepterait-il de répondre à une autre enquête ?* : | { () Oui | (X) <b>Non }
     . | Métiers déclarés dans les journeaux de bord/fiches de pêche : | ^Aucun^
     . | Habitudes de vente à la criée : | ^Partie en criée^
     }
  } . {{+
                           {
                           <font color=grey size=10>Stratégie
                           ACTIFLOT démarrage le 01/01/2019
                           }}
                           {+
                           {
                           <font color=grey size=10>Observateur(s)
                           Obs1
                           <font color=grey size=10>Groupe XX
                           --
                           <font color=grey size=10><&calendar>Créé le 20/03/2023 17:08
                           <font color=grey size=10><&clock>Mis à jour le 20/03/2023 17:08:31
                           .
                           <font color=grey size=10>Mode saisie <b>bureau
                           .
                           [ Terminer la saisie     ]
                           }}}
    <b><&chat> Commentaires (4)
         {+ <font color=grey size=10>Saisissez votre commentaire                                                                                                                   <&X>
            .
            .
         }
         .
         {+ <font color=DarkCyan>Obs1 : <font color=black> Hélice cassée fin 2021
            .
            <font color=grey size=10>Il y a 3 ans                                                                                                <&X>Répondre Modifier Supprimer
         }
         .
         {+ <font color=DarkCyan>Obs1 : <font color=black> Sort souvent avec Jean (BIBAS) --> Pêchent également sur ensemble sur BIBAS
            de temps en temps à ERU
            .
            <font color=grey size=10>Il y a 4 ans                                                                                                <&X>Répondre Modifier Supprimer
         }
         .
         {+ <font color=DarkCyan>Obs2 : <font color=black> Conversation téléphonique
            .
            <font color=grey size=10>Il y a 5 ans                                                                                                                                <&X>Répondre
         }
         .
         {+ <font color=DarkCyan>Obs3 : <font color=black> Appel sans réponse
            .
            <font color=grey size=10>Il y a 7 ans                                                                                                                                 <&X>Répondre
         }
         }
         .





  .
  --
  { [Fermer] | [<&reload> Réinitialiser] | [Sauvegarder] }
}
@endsalt