@startsalt
{
  Navire : <b>LIEU IMMAT - 123456 - VESSEL1 - Activité 2022
  --
  {/ <&info>Général | Navire | <b><&calendar>Calendrier (4)| <&cog>Métiers (2)) | <font color=grey>Carte}
  ..
  {<&plus> <&elevator> <&expand-down> }
  {<b>Calendrier d'activité}
	{S-
	{#
     . | <b>Janvier | <b>Février | <b>Mars | <b>Avril| ... | <b>Décembre
     Armateur | 12345 - DUPOND ERIC | 12345 - DUPOND ERIC | 12345 - DUPOND ERIC | 12345 - DUPOND ERIC | . | . | .
     Lieu d'immatriculation | MA - Marseille | MA - Marseille | MA - Marseille | MA - Marseille | . | . | .
     Actif ?* | ^Inactif    ^| ^Inactif                       ^| ^Actif                                      ^ | ^Actif                                      ^| . | . | .
     Port d'exploitation* | ^JMA - La Matrague de Montredon^ | ^JMA - La Matrague de Montredon^ | ^JMA - La Matrague de Montredon             ^ | ^JMA - La Matrague de Montredon             ^| . | . | .
     Nombre de jours de mer | . | . | 10 | 15 | . | . | .
     Nombre de jours de pêche | . | . | 10 | 15 | . | . | .
     Nombre de personnes à bord | . | . | 2 | 2 | . | . | .
     Métier #1 <&chevron-top> | . | . | ^GTRMZZ - Trémails à poissons               ^ | ^GTRMZZ - Trémails à poissons               ^ | . | . | .
     <U+0020><U+0020>Zone de pêche #1 | . | . | ^MD11 - 3 à 12 milles, région LR, partie Sud^| ^MD11 - 3 à 12 milles, région LR, partie Sud^ | . | . | .
     <U+0020><U+0020>Gradient côte* <&chevron-top>| . | . | ^3-12 Mil. - 3 à 12 milles                  ^| ^3-12 Mil. - 3 à 12 milles                  ^ | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Profondeur | . | . | ^30-50m - Profondeur 30 à 50 mètres         ^ | ^30-50m - Profondeur 30 à 50 mètres         ^ | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Zone proche | . | . | ^Filière                                    ^ | ^Filière                                    ^ | . | . | .
     <U+0020><U+0020>Zone de pêche #2 | . | . | . | . | . | .
     <U+0020><U+0020>Gradient côte <&chevron-top>| . | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Profondeur | . | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Zone proche | . | . | . | . | . | . | .
     Métier #2 <&chevron-top>| . | . | ^GTRNEP - Trémails à langoustines           ^ | . | . | . | .
     <U+0020><U+0020>Zone de pêche #1 | . | . | ^MD11 - 3 à 12 milles, région LR, partie Sud^|.| . | . | .
     <U+0020><U+0020>Gradient côte <&chevron-top>| . | . | ^3-12 Mil. - 3 à 12 milles                  ^|.| . | . | .
     <U+0020><U+0020><U+0020><U+0020>Profondeur | . | . | ^30-50m - Profondeur 30 à 50 mètres         ^|.| . | . | .
     <U+0020><U+0020><U+0020><U+0020>Zone proche | . | . | ^Filière                                    ^|.| . | . | .
     <U+0020><U+0020>Zone de pêche #2 | . | . | . | . | . | . | .
     <U+0020><U+0020>Gradient côte <&chevron-top>| . | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Profondeur | . | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Zone proche | . | . | . | . | . | . | .
    }
    }
    .
    ==
  {<&caret-bottom> <&elevator> <&expand-down> <&box><b>                                                      Prédocumentation</b> | . | . | . | . | . | . | . | . | . | . | . | . | . | . | {  [X]Enquête N-1 | [X]Sacrois-ObsDeb }}
  	{#
     . | <b>Janvier | <b>Janvier | <b>Février | <b>Février | ... | <b>Décembre
     Source | <b>Enquête N-1 | <b>Sacrois-ObsDeb | <b>Enquête N-1 | <b>Sacrois-ObsDeb | . | .
     Actif ? | Inexistant | . | Inactif | Actif | . | .
     Port exploitation | . | . | JMA - La Matrague de Montredon | JMA - La Matrague de Montredon | . | .
     Nombre de jours de mer | . | . | . | 10 | . | .
     Nombre de jours de pêche | . | . | . | 10 | . | .
     Nombre de personnes à bord | . | . | . | 2 | . | .
     Métier #1 <&chevron-top> | . | . | .| GTRMZZ - Trémails à poissons | . | .
     <U+0020><U+0020>Zone de pêche #1 | . | . | .| MD11 - 3 à 12 milles, région LR, partie Sud | . | .
     <U+0020><U+0020>Gradient côte <&chevron-top> | . | . | .| 3-12 Mil. - 3 à 12 milles | . | .
     <U+0020><U+0020><U+0020><U+0020>Profondeur | . | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Zone proche | . | . | . | . | . | . | .
     <U+0020><U+0020>Zone de pêche #2 | . | . | . | . | . | . | .
     <U+0020><U+0020>Gradient côte | . | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Profondeur | . | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Zone proche | . | . | . | . | . | . | .
     Métier #2 <&chevron-top> | . | . | . | . | . | .
     <U+0020><U+0020>Zone de pêche #1 | . | . | . | . | . | .
     <U+0020><U+0020>Gradient côte <&chevron-top> | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Profondeur | . | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Zone proche | . | . | . | . | . | . | .
     <U+0020><U+0020>Zone de pêche #2 | . | . | . | . | . | . | .
     <U+0020><U+0020>Gradient côte <&chevron-top> | . | . | . | . | . | . | .
     <U+0020><U+0020>Profondeur | . | . | . | . | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Zone proche | . | . | . | . | . | . | .
     }
     .
  --
  { [Fermer] | [<&reload> Réinitialiser] | [Sauvegarder] }
}
@endsalt