@startsalt
{
  <b>136794 - SONNY NINO MATHILDE 3 - 2022
  --

  {/ Général | Calendrier | Métiers | <b>Commentaires }
  ..

    {<b>Commentaires
     {+ 19.01.2017 : Appel sans réponse
        08/03/2019 : Conversation téléphonique
        2020 : Sort souvent avec Jean (BIBAS) --> Pêchent également sur ensemble sur BIBAS de temps en temps à ERU
        12/02/2023 : Hélice cassée fin 2023
        .
        .
        .
        .
        .
     } | . |
     {+
                { <font color=grey size=10>Saisisseur
                Adelaide GAMON
                <font color=grey size=10>Groupe EI
                --
                <font color=grey size=10><&calendar>Créé le 20/03/2023 17:08:31
                <font color=grey size=10><&clock>Mis à jour le 20/03/2023 17:08:31
                .
                <font color=grey size=10>Mode saisie <b>bureau
                .
                [ Terminer la saisie]
     }}
    }
  --
  { [Fermer] | [Sauvegarder] }
}
@endsalt