@startsalt
{

  {<b>Calendriers d'activité                                                                                                                                                                                                          <&plus> <&reload> Y {[2022 <&chevron-bottom>]}}
   --

    {
        Lieu d'immatriculation : | . | ^ MA - Marseille               ^ | . | . | Port d'exploitation : | . | ^JMA - La Madrague de Montredon^
        .
        Type de navire : | . | ^ Navire de pêche professionnel^ | . | . | Navire : | . | ^ 123456 - SONNY               ^
        .
        Objectif d'enquête directe ? :   | . |^Oui                           ^|  . | . | Objectif d'enquête éco ? :   | . | { () Oui | (X) <b>Non}
        .
        Organisme observateur :   | . |^ Ifremer                      ^ |  . | . | Observateur :   | . | ^ Nicolas DUPOND               ^
        .
        Etat : | . | ^Qualifié                      ^ |  . | . | Niveau de qualité :   | . | ^                              ^
    }

  --
  {2 résultats  {}[<&caret-bottom>] | [Fermer] | [Appliquer]}}
}
@endsalt
