@startsalt
{
  Navire : <b>LIEU IMMAT - 123456 - VESSEL1 - Activité 2022
  --
{/ <b><&info>Général | Navire | <&calendar>Calendrier | <&cog>Métiers | <font color=grey>Carte}

  ..
  .
  {{
<font color=grey>Objectif d'enquête directe ?* | { (X) <font color=grey><b>Oui | () <font color=grey>Non }
    Enquête éco ?* | { (X) <b>Oui | () Non }} |
  }
.
    <b>Observateur(s)
       {
       . | ^Observateur1 ^ | . |  . | . | . | . | . | <&plus> <&x>
       }
  .
  {
  <b>Caractéristiques de l'enquête
     {
     . | Qualification de l'enquête* : | ^Directe  ^
     . | Fiabilité de l'enquête* : | ^Fiable   ^
     . | Inactivité annuelle confirmée par l'observateur : | { () Oui | (X) <b>Non }
     . | Le professionnel accepterait-il de répondre à une autre enquête ?* : | { () Oui | (X) <b>Non }
     . | Métiers déclarés dans les journeaux de bord/fiches de pêche : | ^Aucun^
     . | Habitudes de vente à la criée : | ^Partie en criée^
     }
  } . {{+
                           {
                           <font color=grey size=10>Stratégie
                           ACTIFLOT démarrage le 01/01/2019
                           }}
                           {+
                           {
                           <font color=grey size=10>Observateur(s)
                           Obs1
                           <font color=grey size=10>Groupe EI
                           --
                           <font color=grey size=10><&calendar>Créé le 20/03/2023 17:08
                           <font color=grey size=10><&clock>Mis à jour le 20/03/2023 17:08:31
                           .
                           <font color=grey size=10>Mode saisie <b>bureau
                           .
                           [ Terminer la saisie     ]
                           }}}
    <b>Commentaires :
         {+ 19.01.2017 : Appel sans réponse
            08/03/2019 : Conversation téléphonique
            2020 : Sort souvent avec Jean (BIBAS) --> Pêchent également sur ensemble sur BIBAS
            de temps en temps à ERU
            12/02/2022 : Hélice cassée fin 2022
            .
            .
            .
            .
            .
         }
  .
  --
  { [Fermer] | [<&reload> Réinitialiser] | [Sauvegarder] }
}
@endsalt