@startsalt
{
{<b>Calendriers d'activité                                                                                                           <&plus> <&reload> Y {[2022 <&chevron-bottom>] {* ...
                                                                                                                                                                                      ... |  <&signal>Editer le rapport ... <&chevron-right> | - | <b>Types de rapport | - | Formulaire vierge | Formulaire avec données | Rapport d'avancement }} }
  --


}
@endsalt