@startsalt
{
  Navire : <b>SONNY - 123456 - MA - 7,81 m - 2022
  --
  {/ Général | Mois d'activité (4) | <b>Métiers (2) | Zones d'activité}
  ..
  { <&plus> <&trash> }
  {# [ ]. |Métier | {<b>Maillage de l'engin (logbook) (mm)
                engin -
                inconnue -
                Déclaration d'un professionnel} |
              {<b>Maillage étiré de l'engin (mm)
                engin -
                plus petite maille -
                Déclaration d'un professionnel} |
              {<b>Maillage étiré de l'engin (mm)
                engin -
                plus grande maille -
                Déclaration d'un professionnel} |
              {<b>Longueur levée (m)
                engin -
                totale -
                Déclaration d'un professionnel}
     [X]. | GTRMZZ - Trémails à poissons | 100 | 97 | 103 | .
     [ ]. | GTRNEP - Trémails à langoustines | . | 57 | . | 100
  }

  { [Fermer] | [Sauvegarder] }
}
@endsalt