@startsalt
{
  <b>Calendriers d'activité                                                                                        <&plus>
  ..
	{#

     [  ] | <b># | <b>Etat | <b>Navire   | <b> Année | <b> Saisisseur | .
     [  ] | 120 | <b>   / | 136794 - SONNY NINO MATHILDE 3 | 2022 | Obs1 | .
     [  ] | 122 | <b>   / | CN123456 - Vessel 3 | 2022 | Obs3 | <&comment-square>
    }

}
@endsalt