@startsalt
{
{<b>Calendriers d'activité                                                                                                           <&plus> <&reload> Y {[2022 <&chevron-bottom>] {* ...
                                                                                                                                                                                      ... |  <&globe>Zone de compétence ... <&chevron-right> | - | [X] Activer la zone de compétence   | - | Corse | Guadeloupe | Guyane | La Réunion | <&check> Martinique | Mayotte | Méditerranée | Mer du nord manche atlantique | Saint Pierre et Miquelon }} }
  --


}
@endsalt