@startsalt
{
  Navire : <b>LIEU IMMAT - 123456 - VESSEL1 - Activité 2022
  --
  {/ <&info>Général | Navire | <b><&calendar>Calendrier (4)| <&cog>Métiers (2)) | <font color=grey>Carte}
  ..
  {<&plus> <&elevator> <&expand-down> }
  {<b>Calendrier d'activité}
	{S-
	{#
     . | <b>Janvier | <b>Février | <b>Mars | <b>Avril| ... | <b>Décembre
     Armateur | 12345 - DUPOND ERIC | 12345 - DUPOND ERIC | 12345 - DUPOND ERIC | 12345 - DUPOND ERIC | . | . | .
     Lieu d'immatriculation | MA - Marseille | MA - Marseille | MA - Marseille | MA - Marseille | . | . | .
     Actif ?* | ^Inactif    ^| ^Inactif                       ^| ^Actif                                      ^ | ^Actif                                      ^| . | . | .
     Port d'exploitation* | ^JMA - La Matrague de Montredon^ | ^JMA - La Matrague de Montredon^ | ^JMA - La Matrague de Montredon             ^ | ^JMA - La Matrague de Montredon             ^| . | . | .
     Nombre de jours de mer | . | . | 10 | 15 | . | . | .
     Nombre de jours de pêche | . | . | 10 | 15 | . | . | .
     Nombre de personnes à bord | . | . | 2 | 2 | . | . | .
     Métier #1 <&chevron-top> | . | . | ^GTRMZZ - Trémails à poissons               ^ | ^GTRMZZ - Trémails à poissons               ^ | . | . | .
     <U+0020><U+0020>Zone de pêche #1 | . | . | ^MD11 - 3 à 12 milles, région LR, partie Sud^| ^MD11 - 3 à 12 milles, région LR, partie Sud^ | . | . | .
     <U+0020><U+0020>Gradient côte* <&chevron-top>| . | . | ^3-12 Mil. - 3 à 12 milles                  ^| ^3-12 Mil. - 3 à 12 milles                  ^ | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Profondeur | . | . | ^10-30m - Profondeur 10 à 30 mètres^| ^30-50m - Profondeur 30 à 50 mètres^ | . | . | .
     <U+0020><U+0020><U+0020><U+0020>Zone proche| . | . | ^DCP^| ^Filière^ | . | . | .
     Zone de pêche  #2 | . | . | . | . | . | .
     Gradient côte* <&chevron-bottom>| . | . | . | . | . | . | .
     Métier #2 <&chevron-top>| . | . | ^GTRNEP - Trémails à langoustines           ^ | . | . | . | .
     Zone de pêche  #1 | . | . | ^MD11 - 3 à 12 milles, région LR, partie Sud^|.| . | . | .
     Gradient côte* <&chevron-bottom>| . | . | ^3-12 Mil. - 3 à 12 milles                  ^|.| . | . | .
     Zone de pêche  #2 | . | . | . | . | . | . | .
     Gradient côte* <&chevron-bottom>| . | . | . | . | . | . | .
    }
    }
  --
  { [PREDOCUMENTATION <&chevron-top> ] | . | . | . | . | . | . | . | . | [Fermer] | [<&reload> Réinitialiser] | [Sauvegarder] }
}
@endsalt