@startsalt
{

  {/  Détails | <b> Capture Bâbord | <b> Capture Tribord }

  .

    {
      Engin bâbord : { ^ Chalut standard    ^ }
      Poids total capture (kg) :  | "       "
      Poids total rejet (kg) :  | "       "
    }

    {/ <b> Partie retenue | Partie rejetée }
	{#
      [ <&plus> ] |  .              | . | . | . | . | .
      # | <b>Espèce commerciale     | <b>Catégorie | <b>Poids total (kg)     |  <b>Taux échant  | <b>Poids échant. | <b>Nb indiv échant.
      4 | ^MNZ- Baudroie             ^ | ^     10 ^ |  50   |  .   |   10          | 4
      3 | ^MNZ- Baudroie             ^ | ^     30 ^ |  50   |  .   |   10          | 4
      2 | ^NEP - Langoustine commune ^ | ^ Petite ^ |  30   |  1/3 |   <i>10       | 4
      1 | ^SOX - Sole                ^ | .          |  50   |  .   |   10          | 4
    }

  --

  {
    [Annuler] | [Sauvegarder]
  }
}
@endsalt
