@startsalt
{

  {/ <b> Détails | Capture }
  ..

    {
      { Engin / espèce ciblée : | ^ OTT - Chalut jumeau à panneaux ^ | ^ Espèce cible ^ }

      {
        Début pêche : | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
        Fin pêche : | ^ Date / Heure ^ | "Latitude   " | "Longitude   "
      }
    }

    <b>Caractéristiques :

    {
      . | Engin bâbord : { ^ Chalut standard                    ^ }
      . | Engin tribord : { ^ Chalut sélectif panneau maille carré ^ }
      . | Mesures individuelles ? { [<b>Oui] | [Non] }
      . | Déroulement normal ? { [<b>Oui] | [Non] }
    }

    {
        <b>Commentaire :

        { "                                                                    "}
    }

  --

  {
    [Annuler] | [Sauvegarder]
  }
}
@endsalt
