@startsalt
{
  <b>Metiers utilisés
  ..
  {<&magnifying-glass> {+  "  Rechercher un métier "    } }
  .
  {
    {+
        AQUCUX - Acquaculture
        FIXAEMP - Active
        FIXALUB - Active trap
        FIXSBSX - Static trap
        GHTRAQ - Hoop/tangel
        GNCCGX - Encircling
        LHMEMP - Handlines
        LHPDPX - Handlines
    } |<&sort-ascending>
  }
  .| [<&star> 12 derniers mois] | [<&plus>]
}
@endsalt
