@startsalt
{
  <b> Immat Navire - Lieu - Date fin marée
  ..
  .
  Code du metier*    | { ^LLSKH - Longlines...^ }
  .
  <b>Autres caractéristiques:
  Nombre d'engin*     | { " 5 " }
  .
  Paramètre propre à l'engin :
  <i>(le paramètre adapté s'affiche en fonction du type d'engin sélectionné)
    * Nombre d'hameçons      | { " 10 " }
    * Nombre de casiers      | { " 3 " }
    * Longueur de filet (m)  | { " 30 " }
  .
  Temps passé à pêcher (en jour de mer) <i>(1 jour par défaut)  | { "  1  " | jour(s) | "  0  " | minute(s) }
  Profondeur minimum de pêche de l'engin (m)  | { " 25 " }
  Profondeur maximum de pêche de l'engin (m)  | { " 40 " }
  .
  Commentaires              | { "commentaires       "}
  .
  Capture débarquée par métier |  |  {[<&layers> Entrer la capture]}

  -- | --

  . | {[Annuler] | [Ajouter]}
}
@endsalt
