@startsalt
{
  <b> Immat Navire - Lieu - Date fin marée
  ..
  {/ General trip | <b>Effort | Capture débarquée | Vente | Dépenses }
  .
  [] Filter on metiers used the last 12 mois
  (<i>Pur filtrer les métiers sir les 12 derniers mois, cliquer sur "+"
  <i>une fenêtre pop-up s'ouvre alors en mode dynamique avec la liste des métiers)
  .
  {[<&plus>]  | [<&trash>]}

  {#
    [ ] |  # | <b>Metier                | <b>Nb engin | <b>Nb hameçons/             | <b>Tps passé à pêcher | <b>Profondeur min | <b>Profondeur max  | <b>Commentaire    | <b>Capture débarquée
    .   |  . | .                        | .           | <b>casiers/long. filet (m)  | en jour de mer        | <b>engin (m)      | <b>engin (m)       | <b>(optionnel)    | <b>par métier
    [X] |  1 | FIXABSX - Active trap... | 10          | .                           | 1 j 0 m               | 25                | 30                 | <&comment-square> | {[<&layers> Entrer la capture]}
    [ ] |  2 | GENLOS - Gillnets...     | 1           | 20                          | 1 j 0 m               | 10                | 20                 | <&comment-square> | {[<&layers> Entrer la capture]}
    [ ] |  3 | LLSKH - Longlines...     | 5           | 30                          | 1 j 0 m               | 25                | 40                 | <&comment-square> | {[<&layers> Entrer la capture]}
  }
  -- | --

  {[Sauvegarder] | [Saisir les efforts pour un autre navire]}
}
@endsalt


