@startsalt
{
  <b> Immat Navire - Lieu - Date fin marée - Métier
  ..
  {/ General trip | Effort | <b>Capture débarquée | Vente | Dépenses }
  .
  {<&beaker> Filter by effort | { ^FIXABSX - Active trap for Vyey^ } | <&spreadsheet> | [Edit] | [New]}
  -- | --
  .
  {/ <b>Capture par espèce | Capture en paquet }
  .
  {
  <b>Capture débarquée par effort
  {[<&plus>]  | [<&sort-ascending>] | [<&minus>]}

  {#
  # | Metier                          | <b>Espèce commerciale         | <b>Poids Ech. (kg)   | <b>NB indiv | <b>Packaging | <b>Preservation | <b>Presentation | <b>Cat Tri
  1 | FIXABSX - Active trap for Vyey  | Anba Iasann - PWT             | 200.0                | 45          | Unit         | Frais           | Entier          | Unsorted
  2 | FIXABSX - Active trap for Vyey  | Barwa - LXN                   | 26.0                 | 3           | Unit         | Frais           | Entier          | Unsorted
  }
  }
  .
  -- | --
  .
  {/ Capture par espèce | <b>Capture en paquet }
  .
  {
  <b>packets saisis par effort
  {[<&plus>]  | [<&spreadsheet>] | [<&minus>]}

  {#
  # | Metier                          | <b>ID Lot* | <b>Nombre de paquets*)   | <b> Poids (kg)* | <b>Composition | <b>Detail
  1 | FIXABSX - Active trap for Vyey  | Lot 1      | 5                        | 484.0           | <&layers>      | <&comment-square>
  }
  }
  .
  -- | --
  {{[Fermer et retour à l'observation] | [Saisir la vente]}}
}
@endsalt
