@startsalt
{
  <b>Navire FRA0001114 / Débarquement 01/02/2019 23:59
  ..
  {/ General trip | Effort | <b>Capture débarquée }
  .
  {<&beaker> Filter by effort | { ^FIXABSX - Active trap for Vyey^ } | <&spreadsheet> | [Edit] | [New]}
  .
  {
  <b>Capture débarquée par effort
  {[<&plus>]  | [<&sort-ascending>] | [<&minus>]}

  {#
  # | <b>Espèce commerciale         | <b>Poids Ech. (kg)   | <b>NB indiv | <b>Packaging | <b>Effort
  1 | Anba Iasann - PWT     | 200.0             | 45 | Unit | FIXABSX - Active trap for Vyey - FIXA - Active trap - 01/10/2019 00:00
  2 | Barwa - LXN     | 26.0             | 3 | Unit | FIXABSX - Active trap for Vyey - FIXA - Active trap - 01/10/2019 00:00
  }
  }
  .
  -- | --
  {
  <b>packets saisis par effort
  {[<&plus>]  | [<&spreadsheet>] | [<&minus>]}

  {#
  # | <b>ID | <b>Nombre de paquets*)   | <b> Poids (kg)* | <b>Effort* | <b>Composition | <b>Detail
  1 | 1     | 5             | 484.0 | FIXABSX - Active trap for Vyey - FIXA - Active trap - 01/10/2019 00:00 | <&layers> | <&comment-square>
  }
  }
  .
  {{[Fermer et retour à l'observation] | [Saisir la vente]}}
}
@endsalt
