@startsalt
{
  <b> Immat Navire - Lieu - Date fin marée - Métier
  ..
  {/ General trip | Effort | Capture débarquée | Vente | <b>Dépenses }
  .
  {Estimation des dépenses totales (Devise) : <&arrow-circle-right> {+"           " } <&calculator> | {Coût total calculé  {<color:blue> 354.0} Devise }}
  -- | --
  <b>Détail des dépenses
  ..
  {
  .
  <b>Fluides de fonctionnement :
    {
    .                   | {Volume (L)} | {Prix (Devise/L)} | {Prix total (Devise)}
    { ^Carburant^ }     | { <&arrow-circle-right> {+"           " } <&calculator>} | {<&arrow-circle-right> {+"           " } <&calculator>} | {<&arrow-circle-right> {+"           " } <&calculator>}
    huile de moteur :   | { <&arrow-circle-right> {+"           " } <&calculator>} | {<&arrow-circle-right> {+"           " } <&calculator>} | {<&arrow-circle-right> {+"           " } <&calculator>}
    huile hydraulique : | { <&arrow-circle-right> {+"           " } <&calculator>} | {<&arrow-circle-right> {+"           " } <&calculator>} | {<&arrow-circle-right> {+"           " } <&calculator>}
    }
  }
  .
  {
  <b>Frais annexes :

    Frais de débarquement | { <&arrow-circle-right> {+"           " } <&calculator>} | {Devise}
    Alimentation          | { <&arrow-circle-right> {+"           " } <&calculator>} | {Devise}
    Perte d'engin         | { <&arrow-circle-right> {+"           " } <&calculator>} | {Devise}
    Autre                 | { <&arrow-circle-right> {+"           " } <&calculator>} | {Devise}
    .
    Commentaires              | { "commentaires       "}
  }
  .
  {
  <b>Glace utilisée :
    {Quantité de glace | <&arrow-circle-right> {+"           " } <&calculator>}  | { ^Unité (au kg ou par sac)^ } | { Coût de la glace | <&arrow-circle-right> {+"           " } <&calculator> | Devise}
  }
  .
  {
  <b>Appâts :
    { ^Type d'appât^ } | {Nombre d'appâts <&arrow-circle-right> {+"           " } <&calculator>} | { ^Unité de conditionnement (kg, unité, sac ou paquet)^ } | { Coût des appâts | <&arrow-circle-right> {+"           " } <&calculator> | Devise}
    { ^Type d'appât^ } | {Nombre d'appâts <&arrow-circle-right> {+"           " } <&calculator>} | { ^Unité de conditionnement (kg, unité, sac ou paquet)^ } | { Coût des appâts | <&arrow-circle-right> {+"           " } <&calculator> | Devise}
    { ^Type d'appât^ } | {Nombre d'appâts <&arrow-circle-right> {+"           " } <&calculator>} | { ^Unité de conditionnement (kg, unité, sac ou paquet)^ } | { Coût des appâts | <&arrow-circle-right> {+"           " } <&calculator> | Devise}
  }
  .
  -- | --
  {{[Fermer et retour à l'observation] | [Enregistrer]}}
}
@endsalt
