@startsalt
{
  <b>Nouveau débarquement
  ..
  {/ <b>General trip | Effort | Capture débarquée }
  .
  Programme de collecte:    | { ^SIH-OBSDEB^ }
  Navire:                   | { ^FRA0001114^ | <&plus> }
  Lieu de débarquement de la marée*:     | { ^MA - Mahé Island^ }
  Date/Heure début de marée:  | { ^01/02/2019^ | ^00:00^ }
  Date/Heure fin de marée:  | { ^01/02/2019^ | ^23:59^ }
  Date/Heure débarquement:  | { ^01/02/2019^ | ^23:59^ }
  Observateurs :            | { ^Observateur #1^ | [<&plus>] | [<&x>]}
  Autres caractéristiques:  | { Paramètre 1 (ex: Nombre d'homme à bord) : | "   1  " }
  .                         | { Paramètre 2 : | ^Valeur qualitative^ }
  .                         | { Paramètre 3 (ex: Principale zone de pêche) : | ^Valeur qualitative^ }
  .                         | { Paramètre 4 (ex: Gradient de distance à la côte): | ^Valeur qualitative^ }
  .                         | { Paramètre 5 (ex: Force du vent) : | ^Valeur qualitative^ }
  .                         | { Paramètre 6 (ex: Force du courant): | ^Valeur qualitative^ }
  .
  Commentaires              | { "commentaires       "}

  -- | --

  .                          | {[Annuler] | [Sauvegarder]}
}
@endsalt
