@startsalt
{
  <b>Metier(s) utilisé(s)
  ..
  [] Filtrer sur les métiers utilisés les 12 derniers mois
  .
  {<&beaker> <&arrow-circle-right> {+  "                              "    }<&sort-ascending>}
  .
  {
  {+
  AQUCUX - Acquaculture
  FIXAEMP - Active
  FIXALUB - Active trap
  FIXSBSX - Static trap
  GHTRAQ - Hoop/tangel
  GNCCGX - Encircling
  LHMEMP - Handlines
  LHPDPX - Handlines
  }  <&arrow-thick-left> <&arrow-thick-right> {+
  AQUCUX - Acquaculture
  FIXSBSX - Static trap
  }
  }
}
@endsalt
