@startsalt
{
  <b>Nouvel engin (intégrer le métier au niveau de l'effort ?)
  ..
  .
  Code du metier*:    | { ^LLSKH - Longlines...^ }
  Code de l'engin*:     | { ^LL - Longlines...^ | <&plus> }
  Numéro de l'engin*:     | { " 3 " }
  Nombre d'engin*:     | { " 5 " }
  Nombre d'hameçons / de casiers / longueur de filet (m):  | { " 30 " }
  Temps passé à pêcher (en jour de mer):  | { "  1  " | jour | "  0  " | m??? }
  Profondeur minimum de pêche de l'engin (m):  | { " 25 " }
  Profondeur maximum de pêche de l'engin (m):  | { " 40 " }
  .
  Commentaires              | { "commentaires       "}
  .
  Capture débarquée par métier |  |  {[<&layers> Entrer la capture]}

  -- | --

  . | {[Annuler] | [Ajouter]}
}
@endsalt
