@startsalt
{
  <b> Echantillonage des paquets | [Fermer]
  -- | --
  {(X) Saisie mode rafale  }
  {
    .
    {ID Lot| " 2  " | Nombre de paquet : {"<color:blue><i>55 "} | {Poids total des paquets calculé { "<color:blue><i>527,10"}}}
    {Nombre d'échantillon saisi : {"<color:blue><i>6"} | {<i>Valeur s'incrémente toute seule (6=valeur maximum par defaut pour SFA)} }
  }
.
..
  {+
  <b>Ajouter un échantillon :
  Poids de l'échantillon (kg):              | { "          160  "  }
  .
  Espèce commerciale*:       | { ^ Anba lasann ^ | [] Valeur par défaut }
  % (Σ=100) :               | { "    10    " }
  . |  {[Ajouter (= Entrer)] | [Annuler la dernière]}
  .
      {#
        # | <b>Lot de paquets  | <b>Espèce commerciale  | <b>% (Σ=100) | .
        2 | Lot 2 - 55 paquets | Anba lasann            | 10           | <&trash>
        1 | Lot 2 - 55 paquets | Albakor                | 90           | <&trash>
      } | {<color:red><i>Si la Σ n'est pas égal à 100 %,
      <color:red><i>alors il n'est as possible de valider l'échantillon }
  .
  {[Nouvel échantillon (= Valider)] | [Fin échantillonnage ]}
  }
  .
  -- | --
  .
  {+
    <b>Poids estimé calculé par espèce pour le paquet (kg) :
    {#
        # | <b>Lot de paquets  | <b>Espèce commerciale*  | <b>Poids (kg)*
        1 | Lot 2 - 55 paquets | Albakor                 | <color:blue><i>241.03
        2 | Lot 2 - 55 paquets | Anba lasann             | <color:blue><i>180.97
        3 | Lot 2 - 55 paquets | Babonn Zonn             | <color:blue><i>105.10
    }
  }

  -- | --
  {{[Fermer ] | [Sauvegarder]}}
}
@endsalt
