@startsalt
{
  <b>Nouvelle marée
  ..
  {/ <b>General trip | Effort | Capture débarquée | Vente | Dépenses }
  .
  Programme de collecte*:    | { ^SIH-OBSDEB^ }
  Navire*:                   | { ^FRA0001114^ }
  Lieu de débarquement de la marée*:     | { ^MA - Mahé Island^ }
  Date/Heure début de marée*:  | { ^_ _/_ _/_ _ _ _^ | ^_ _:_ _^ }
  Date/Heure fin de marée*:  | { ^_ _/_ _/_ _ _ _^ | ^_ _:_ _^ }
  Observateurs* :            | { ^Observateur #1^ | [<&plus>] | [<&x>]}
  Autres caractéristiques:  | { Paramètre 1 (ex: Nombre d'homme à bord) : | "   1  " }
  .                         | { Paramètre 2 : | ^Valeur qualitative^ }

  .
  Commentaires              | { "commentaires       "}

  -- | --

  .                          | {[Sauvegarder] | [Saisir les efforts]}
}
@endsalt
