@startsalt
{
  <b>Nouveau débarquement
  ..
  {/ <b>General trip | Effort | Capture débarquée | Vente | Dépenses }
  .
  Programme de collecte:    | { ^SIH-OBSDEB^ }
  Navire:                   | { ^FRA0001114^ | <&plus> }
  Lieu de débarquement de la marée*:     | { ^MA - Mahé Island^ }
  Date/Heure début de marée:  | { ^01/02/2019^ | ^00:00^ }
  Date/Heure fin de marée:  | { ^01/02/2019^ | ^23:59^ }
  Observateurs :            | { ^Observateur #1^ | [<&plus>] | [<&x>]}
  ..
  <b>Autres caractéristiques:
  {+
  Metiers :


  {
    {<&magnifying-glass> {+  "  Rechercher un métier "    } }
    .
    {
      {+
      {*  Metier : Code - Nom
      Metier : Code - Nom  | <b>Code       -       Nom  | AQUCUX - Acquaculture  | FIXAEMP - Active | LHMEMP - Handlines |  -  | [<&star> 12 derniers mois] | [<&plus>] }
      } | <&sort-ascending>
    }
  }
    }
  Nombre d'homme à bord           | { "   1  " }
  Principale zone de pêche        | { ^Valeur qualitative^ }
  Gradient de distance à la côte  | { ^Valeur qualitative^ }
  Force du vent                   | { ^Valeur qualitative^ }
  Force du courant                | { ^Valeur qualitative^ }
  .
  Commentaires              | { "commentaires       "}

  -- | --

  .                          | {[Annuler] | [Sauvegarder]}
}
@endsalt
