@startsalt
{
  <b>Weekly report of activity 02/02/2019 00:00 - LS-AF - Anse Forban
  ..
  {/ Information générale | Situation des navires | <b>Activités des navires }
  .
  {<b>Navire :            | { ^SZ190 - Ziblo         ^ | [<&plus>]}}
  .
  {+
    {+
        {Metier*:        | { ^FIXABSX - Active trap for Vyey^ | [] Valeur par défaut }  | [<&plus>]| [<&x>]}

        {
            [Lundi   ] | [<b>Mardi   ] | [Mercredi] | [Jeudi   ] | [<b>Vendredi] | [Samedi  ] | [Dimanche]
            <&eye>     | [<&eye>]      | <&eye>     | <&eye>     | [<&eye>]      | <&eye>     | <&eye>
        }
        {Metier*:        | { ^METIER2 - Metier 2            ^ | [] Valeur par défaut }  | [<&plus>]| [<&x>]}

        {
            [Lundi   ] | [<b>Mardi   ] | [Mercredi] | [Jeudi   ] | [<b>Vendredi] | [Samedi  ] | [Dimanche]
            <&eye>     | [<&eye>]      | <&eye>     | <&eye>     | [<&eye>]      | <&eye>     | <&eye>
        }
        .
    }
        {. |  {[Ajouter un navire] | [Annuler la dernière]}}
  }
  .
  .
  {<b>Navire :            | { ^Navire 2         ^ | [<&plus>]}}
  .
  {+
    {+
        {Metier*:        | { ^METIER1 - Metier 1^ | [] Valeur par défaut }  | [<&plus>]| [<&x>]}

        {
            [Lundi     ] | [Mardi    ] | [Mercredi ] | [Jeudi    ] | [Vendredi ] | [Samedi  ] | [Dimanche]
            [<&eye>]     | <&eye>     | [<&eye>]    | <&eye>     | [<&eye>]      | <&eye>     | <&eye>
        }
        .
    }
        {. |  {[Ajouter un navire] | [Annuler la dernière]}}
  }
  .
  {[Fermer et retour à l'observation]}
}
@endsalt
