@startsalt
{
  <b>Weekly report of activity 02/02/2019 00:00 - LS-AF - Anse Forban
  ..
  {/ Information générale | <b>Situation des navires | Activités des navires }
  .
  {SI .| .| [Fermer]
      {
      {+
          <b>Liste navires:
          .
          .
          {{ ^SZ190 - Ziblo         ^ | [<&x>]}}
          .
          {{ ^Vessel 2              ^ | [<&x>]}}
          .
          {{ ^Vessel 3              ^ | [<&x>]}}
          .
          {{ ^Vessel 4              ^ | [<&plus>] | [<&x>]}}
          .
      }
      } |
      {
          {+
            {
                {[<b>Lundi       ]} | {[<b>Mardi       ]} | {[<b>Mercredi    ]} | {[<b>Jeudi       ]} | {[<b>Vendredi    ]} | {[Samedi      ]} | {[Dimanche    ]}
                .
                .
                { ^NA- boat not...^} | { ^IN- boat in ...^} | { ^LD- boat lan...^} | { ^NS- boat not...^} | { ^BR- break down ^} | { ^<i>Situation^} | { ^<i>Situation^}
            }
          }
          {+
            ..
                {
                    { ^DL- one day ...^} | { ^LD- boat lan...^} | { ^NA- boat not...^} | { ^NA- boat not...^} | { ^LD- boat lan...^} | { ^<i>Situation^} |  { ^<i>Situation^}
                }
          }
          {+
            ..
                {
                    { ^IN- boat in ...^} | { ^LD- boat lan...^} | { ^NA- boat not...^} | { ^OUT- boat out  ^} | { ^DL- one day ...^} | { ^<i>Situation^} |  { ^<i>Situation^}
                }
          }
          {+
            ..
                {
                    { ^NA- boat not...^} | { ^DP- boat dep...^} | { ^OUT- boat out  ^} | { ^NA- boat not...^} | { ^LD- boat lan...^} | { ^<i>Situation^} |  { ^<i>Situation^}
                }
          }
      }
  }
  {{[Sauvegarder] | [Saisir une activité]}}
}
@endsalt
