REM INSERTING into SIH2_ADAGIO_DBA.ACTIVITY_CALENDAR2PERSON

INSERT INTO ACTIVITY_CALENDAR2PERSON
(SELECT AC.ID, AC.RECORDER_PERSON_FK FROM ACTIVITY_CALENDAR AC
WHERE AC.PROGRAM_FK = 'SIH-ACTIFLOT'
AND ID NOT IN (SELECT ACTIVITY_CALENDAR_FK FROM ACTIVITY_CALENDAR2PERSON)
AND AC.RECORDER_PERSON_FK IS NOT NULL);

commit;