REM INSERTING into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY

Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.vessel.filter.type.ids','5,1',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.program.strategy.department.enable','false',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.report.form.blank.head.physicalGearPmfm1','Plus petit maillage étiré en mm',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.report.form.footer','Usage obligatoire et confidentiel   ©Ifremer. Système d''informations halieutiques',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.extraction.formats','ACTIMONIT,VESSEL',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.report.progress.tooManyResults.waring','520',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.report.progress.tooManyResults.error','100',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.program.privilege.readonly','true',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.report.form.blank.head.physicalGearPmfm2','Dimension',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.report.enable','true',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.report.types','blank-form,form,progress',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.data.report.color.primary','#bc3287',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.fishingArea.location.level.ids','113,145,114,111,141,105,106',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.report.form.header.left.logo.url','https://sumaris-app.isival.ifremer.fr/assets/img/logo/logo-sih-black.png',sysdate, current_timestamp,'SIH-ACTIFLOT','1');
Insert into SIH2_ADAGIO_DBA.PROGRAM_PROPERTY (ID,LABEL,NAME,CREATION_DATE,UPDATE_DATE,PROGRAM_FK,STATUS_FK) values (PROGRAM_PROPERTY_SEQ.nextval,'sumaris.activityCalendar.report.progress.footer','Usage obligatoire et confidentiel   ©Ifremer. Système d''informations halieutiques',sysdate, current_timestamp,'SIH-ACTIFLOT','1');

commit;